import json

# Load existing data
with open('scenarios_zh.json', 'r', encoding='utf-8') as f:
    zh = json.load(f)
with open('scenarios_en.json', 'r', encoding='utf-8') as f:
    en = json.load(f)
with open('code_maps.json', 'r', encoding='utf-8') as f:
    cm = json.load(f)

# Phase 3 batch 2: Lu Jiuyuan, Wang Yangming, Gu Yanwu, Huang Zongxi, Wang Fuzhi, Dai Zhen, Mo Zi, Zeng Zi, Mo Zi Hou Xue, Bai Gui (10 figures)
new_figures = [
    # H-215: 陆九渊
    {
        "code": "H-LJY-215",
        "name_zh": "陆九渊：象山心学/心即理/四句教/象山/陆子静",
        "name_en": "Lu Jiuyuan: Xiangshan Heart Learning/Heart Is Principle/Four Sentences Teaching/Xiangshan/Lu Zijing",
        "desc_zh": "南宋哲学家，心学鼻祖。以「心即理」三字颠覆程朱「格物穷理」外求之弊，提出「四句教」：①圣人与我同类 ②吾心即是 ③吾心即有 ④尽吾心则圣人矣，建立「内求/直指/当下/成圣」四步心法速成法。",
        "desc_en": "Southern Song philosopher, patriarch of Heart Learning. Overturned Cheng-Zhu 'investigate things exhaust principles' external seeking error with 'heart is principle' three characters, proposed 'Four Sentences Teaching': 1) sages same type as me 2) my heart is it 3) my heart has it 4) exhaust my heart then sage, establishing 'internal seeking/direct pointing/present moment/become sage' four-step heart-method fast-track.",
        "modes": [37, 27, 21, 28, 35],
        "reason_zh": "陆九渊以「心即理」三字颠覆程朱「格物穷理」外求之弊，提出「四句教」：①圣人与我同类 ②吾心即是 ③吾心即有 ④尽吾心则圣人矣，建立「内求/直指/当下/成圣」四步心法速成法。",
        "reason_en": "Lu Jiuyuan overturned Cheng-Zhu 'investigate things exhaust principles' external seeking error with 'heart is principle' three characters, proposed 'Four Sentences Teaching': 1) sages same type as me 2) my heart is it 3) my heart has it 4) exhaust my heart then sage, establishing 'internal seeking/direct pointing/present moment/become sage' four-step heart-method fast-track.",
        "steps_zh": ["本体锚定：锁定「外求理/格物穷理/分心/逐物」为程朱心学主要矛盾，确立「心即理」本体论——「吾心即是圣人心」", "协议标准化：设计「四句教」标准化入道协议——「圣人与我同类/吾心即是/吾心即有/尽吾心则圣人矣」，四步直指人心成圣捷径", "系统集成：建立「不假外求/不假知识/不假工夫/直指人心」四重否定法，以「当下直指」替代「格物穷理」长链条", "工程化传承：确立「象山讲会/门人传授/著述流传/仪式固化」四重传承链路，王柏/王应电/陈献章/王阳明双系传承", "动态校准：设定「不动心/不杂念/不二法门/一以贯之」四重心法底线，确保「心即理」不流于禅宗/主观唯心"],
        "steps_en": ["Ontological Anchoring: Lock 'external seeking li/investigate things exhaust principles/divided heart/chasing things' as Cheng-Zhu heart learning main contradiction, establish 'heart is principle' ontology—'my heart is sage heart'", "Protocol Standardization: Design 'Four Sentences Teaching' standardized entry protocol—'sages same type as me/my heart is it/my heart has it/exhaust my heart then sage', four-step direct-pointing-heart-become-sage shortcut", "System Integration: Establish 'no external seeking/no knowledge assumption/no cultivation assumption/direct pointing heart' four-fold negation method, replace 'investigate things exhaust principles' long chain with 'present moment direct pointing'", "Engineering Transmission: Establish 'Xiangshan lectures/disciple transmission/writings circulation/ritual solidification' four-fold transmission chain, Wang Bo/Wang Yingdian/Chen Xianzhang/Wang Yangming dual-system transmission", "Dynamic Calibration: Set 'unmoved heart/no杂念/non-dual dharma gate/one penetrates all' four-fold heart-method baselines, ensure 'heart is principle' doesn't flow into Zen/subjective idealism"],
        "expected_zh": "建立心学鼻祖范式，形成可速成的直指人心心法工程体系",
        "expected_en": "Establish Heart Learning patriarch paradigm, form fast-track direct-pointing-heart heart-method engineering system",
        "case_zh": "1175年鹅湖会议与朱熹辩论「格物/主敬/天理/人欲」，分道扬镳。立「象山书院」，四方学者云集。核心「心即理」：「宇宙便是吾心，吾心即是宇宙」。四句教：「圣人与我同类/吾心即是/吾心即有/尽吾心则圣人矣」。建「不假外求/直指人心/当下成圣」心法速成法。门人王柏/王应电/陈献章传承，至王阳明「龙场悟道」完成「致良知」体系化。其「心即理/四句教/直指/象山讲会」四维融合，成陆王心学鼻祖，与程朱理学「格物/穷理/主敬/存天理」双峰对峙。",
        "case_en": "1175 Ehu Meeting debated 'investigate things/master reverence/heavenly principle/human desires' with Zhu Xi, parted ways. Founded 'Xiangshan Academy', scholars gathered. Core 'heart is principle': 'universe is my heart, my heart is universe'. Four Sentences: 'sages same type as me/my heart is it/my heart has it/exhaust my heart then sage'. Built 'no external seeking/direct pointing heart/present moment become sage' heart-method fast-track. Disciples Wang Bo/Wang Yingdian/Chen Xianzhang transmitted, until Wang Yangming 'Longchang Enlightenment' completed 'liangzhi' systematization. Their 'heart is principle/four sentences/direct pointing/Xiangshan lectures' four-dimensional fusion became Lu-Wang Heart Learning patriarch, dual-peak confrontation with Cheng-Zhu Neo-Confucianism 'investigate things/exhaust principles/master reverence/preserve heavenly principle'."
    },
    # H-216: 王阳明
    {
        "code": "H-WYM-216",
        "name_zh": "王阳明：心学/知行合一/致良知/龙场悟道/良知即事",
        "name_en": "Wang Yangming: Heart Learning/Unity of Knowledge and Action/Extend Liangzhi/Longchang Enlightenment/Liangzhi Is Affairs",
        "desc_zh": "明代哲学家，心学集大成。以「致良知」完成心学体系化重构，将「良知良能」从先天预设降维为「童心真念当下显现」，提出「知行合一」工程化协议，完成从「先天论」到「现象学」的认知范式跃迁。",
        "desc_en": "Ming philosopher, synthesizer of Heart Learning. Completed Heart Learning systematic reconstruction with 'extend liangzhi', demoted 'liangzhi liangneng' from innate preset to 'child-heart true thought present manifestation', proposed 'unity of knowledge and action' engineering protocol, completing cognitive paradigm leap from 'innate theory' to 'phenomenology'.",
        "modes": [37, 27, 21, 28, 35],
        "reason_zh": "王阳明以「致良知」完成心学体系化重构，将「良知良能」从先天预设降维为「童心真念当下显现」，提出「知行合一」工程化协议，完成从「先天论」到「现象学」的认知范式跃迁。",
        "reason_en": "Wang Yangming completed Heart Learning systematic reconstruction with 'extend liangzhi', demoted 'liangzhi liangneng' from innate preset to 'child-heart true thought present manifestation', proposed 'unity of knowledge and action' engineering protocol, completing cognitive paradigm leap from 'innate theory' to 'phenomenology'.",
        "steps_zh": ["本体锚定：锁定「外求理/格物穷理/分心/逐物」为程朱心学主要矛盾，确立「良知即童心、童心即良知」本体论——「吾心即是圣人心」", "协议标准化：设计「四句教」标准化入道协议——「圣人与我同类/吾心即是/吾心即有/尽吾心则圣人矣」，四步直指人心成圣捷径", "系统集成：建立「不假外求/不假知识/不假工夫/直指人心」四重否定法，以「当下直指」替代「格物穷理」长链条", "工程化传承：确立「象山讲会/门人传授/著述流传/仪式固化」四重传承链路，王柏/王应电/陈献章/王阳明双系传承", "动态校准：设定「不动心/不杂念/不二法门/一以贯之」四重心法底线，确保「心即理」不流于禅宗/主观唯心"],
        "steps_en": ["Ontological Anchoring: Lock 'external seeking li/investigate things exhaust principles/divided heart/chasing things' as Cheng-Zhu heart learning main contradiction, establish 'liangzhi is child-heart, child-heart is liangzhi' ontology—'my heart is sage heart'", "Protocol Standardization: Design 'Four Sentences Teaching' standardized entry protocol—'sages same type as me/my heart is it/my heart has it/exhaust my heart then sage', four-step direct-pointing-heart-become-sage shortcut", "System Integration: Establish 'no external seeking/no knowledge assumption/no cultivation assumption/direct pointing heart' four-fold negation method, replace 'investigate things exhaust principles' long chain with 'present moment direct pointing'", "Engineering Transmission: Establish 'Xiangshan lectures/disciple transmission/writings circulation/ritual solidification' four-fold transmission chain, Wang Bo/Wang Yingdian/Chen Xianzhang/Wang Yangming dual-system transmission", "Dynamic Calibration: Set 'unmoved heart/no杂念/non-dual dharma gate/one penetrates all' four-fold heart-method baselines, ensure 'heart is principle' doesn't flow into Zen/subjective idealism"],
        "expected_zh": "完成心学体系化重构，形成致良知/知行合一/良知即童心/直指人心四维融合的集大成范式",
        "expected_en": "Complete Heart Learning systematic reconstruction, form synthesis paradigm of four-dimensional fusion: extend liangzhi/unity knowledge action/liangzhi is child-heart/direct pointing heart",
        "case_zh": "龙场悟道：「圣人之道，吾性自足，向外求理误也」。立「致良知」体系：「良知者、吾心之本然者也」，「致者、极也、极其良知而已矣」。建「知行合一/致良知/良知即童心/知行合一/格物致知」体系。其「致良知/知行合一/良知即童心/直指人心」四维融合，成陆王心学集大成范式，影响王畿/钱德洪/王艮/罗钦顺/湛若水/李贽/焦竑/顾宪成/高攀龙/黄宗羲/王夫之/颜元/刘宗周/刘元卿/方以智/颜元/李塨/王廷相/罗近溪/甘来苏/熊十力/牟宗三/唐君毅/徐复观心学/新儒家全版图。",
        "case_en": "Longchang Enlightenment: 'sage way, my nature self-sufficient, seeking li externally is error'. Established 'extend liangzhi' system: 'liangzhi is my heart's innate', 'extend means utmost, utmost liangzhi only'. Built 'unity knowledge action/extend liangzhi/liangzhi is child-heart/unity knowledge action/investigate things extend knowledge' system. Their 'extend liangzhi/unity knowledge action/liangzhi is child-heart/direct pointing heart' four-dimensional fusion became Lu-Wang Heart Learning synthesis paradigm, influencing Wang Ji/Qian Dehong/Wang Gen/Luo Qinshun/Zhan Ruoshui/Li Zhi/Jiao Hong/Gu Xiancheng/Gao Panlong/Huang Zongxi/Wang Fuzhi/Yan Yuan/Liu Zongzhou/Liu Yuanqing/Fang Yizhi/Yan Yuan/Li Tiao/Wang Tingxiang/Lu Jinxī/Gan Laisu/Xiong Shili/Mou Zongsan/Tang Junyi/Xu Fuguan Heart Learning/New Confucianism entire map."
    },
    # H-217: 顾炎武
    {
        "code": "H-GYW-217",
        "name_zh": "顾炎武：经世致用/日知录/考据实学/天下兴亡/复社",
        "name_en": "Gu Yanwu: Practical Learning for Governance/Rizhilu/Evidential Real Learning/World Rise Fall/Fushe",
        "desc_zh": "明清之际思想家，考据实学/经世致用双系血脉不可替代。以「经世致用」回应晚明空疏，以「日知录」三十卷建立「博征广引、互证参校」考据技术，将「治史即治国、考据即批判」转化为制度设计的证据链标准，使「治史」直接服务「治国」——清初思想启蒙双峰（黄/顾/王）之首。",
        "desc_en": "Ming-Qing transition thinker, irreplaceable dual lineage of evidential real learning/practical governance learning. Responded to late Ming emptiness with 'practical learning for governance', established 'extensive citation, mutual verification' evidential technique with 'Rizhilu' thirty volumes, transformed 'historiography is governance, evidential research is critique' into evidence chain standard for institutional design, made 'historiography' directly serve 'governance'—first of early Qing intellectual enlightenment twin peaks (Huang/Gu/Wang).",
        "modes": [5, 22, 25, 28, 35],
        "reason_zh": "顾炎武以「经世致用」回应晚明空疏，以「日知录」建立考据实学方法论，将「博征广引、互证参校」考据技术转化为制度设计的证据链标准，使「治史」直接服务「治国」——清初思想启蒙双峰（黄/顾/王）之首。",
        "reason_en": "Gu Yanwu responded to late Ming emptiness with 'practical learning for governance', established evidential real learning methodology with 'Rizhilu', transformed 'extensive citation, mutual verification' evidential technique into evidence chain standard for institutional design, made 'historiography' directly serve 'governance'—first of early Qing intellectual enlightenment twin peaks (Huang/Gu/Wang).",
        "steps_zh": ["本体锚定：锁定「空谈性理/脱离制度/不解民疾」为晚明思想界主要矛盾，确立「经世致用」为破解杠杆——「天下兴亡，匹夫有责」", "协议标准化：重构「义利」关系——「利者、义之本也」，将「义」重构为「利」的长期最优解，建立四维利益演算框架", "系统集成：设计「史为利用而作」史学方法论，以「成败/得失/因果/规律」四维分析模板解读历史，提炼「利用」通则", "工程化传承：建立「通变达权/权衡轻重/因时制宜」四重决策协议，确保「利用」不流于短视功利", "动态校准：主张「因时制宜/因地制宜/因势利导」，以「变通/权衡/试行/推广」四阶段制度迭代协议"],
        "steps_en": ["Ontological Anchoring: Lock 'empty principle talk/detached from institutions/ignorant of people's suffering' as late Ming intellectual main contradiction, establish 'practical learning for governance' as breakthrough lever—'world rise fall, common man has responsibility'", "Protocol Standardization: Reconstruct 'yi-li' relationship—'li is yi's root', reconstruct 'yi' as 'li's long-term optimal solution, build four-dimensional interest calculus framework", "System Integration: Design 'historiography for utility' methodology, interpret history with 'success-failure/gain-loss/causality/patterns' four-dimensional analysis template, extract 'utility' general principles", "Engineering Transmission: Establish 'adaptive flexibility/weighing importance/timeliness' four-fold decision protocol, ensure 'utility' doesn't flow into short-term utilitarianism", "Dynamic Calibration: Advocate 'timeliness/local-adaptability/situational leverage', with 'flexible adaptation/weighing/trial/promotion' four-stage institutional iteration protocol"],
        "expected_zh": "建立考据实学/制度工程双系血脉，为中国近代宪政启蒙提供首个可落地制度蓝图",
        "expected_en": "Establish evidential real learning/institutional engineering dual lineage, provide first implementable institutional blueprint for modern Chinese constitutional enlightenment",
        "case_zh": "著《日知录》《亭林诗文集》《赵氏辟疆亭记》等。核心：「经世致用」、「天下兴亡/匹夫有责」、「日知录」三十卷建立「博征广引、互证参校」考据技术，将「礼/乐/兵/农/工/商/水/土/学/法/典/制」十二大类制度工程化。著《明夷待访录》二十一篇建立「原法/原臣/原置/原爵/原刑/原财/原兵/原学」八大制度重构模块，每模块含「病理诊断→制度处方→操作细则→容错预案」四段式标准结构，为中国近代宪政启蒙提供首个可落地的制度蓝图；创立「史学即政治、考据即批判」东林-浙东学派方法论，影响章学诚/魏源/龚自珍/黄宗羲/王夫之/万斯同/全祖望/黄宗会/黄百家考据史学/制度工程双系血脉不可替代。",
        "case_en": "Authored 'Rizhilu', 'Tinglin Shiwenji', 'Zhaoshi Pijiangting Ji' etc. Core: 'practical learning for governance', 'world rise fall/common man responsibility', 'Rizhilu' thirty volumes established 'extensive citation, mutual verification' evidential technique, engineered twelve major categories: rites/music/military/agriculture/industry/commerce/water/soil/education/law/canon/institutions. Authored 'Mingyi Daifanglu' twenty-one chapters establishing eight major institutional reconstruction modules: original law/ministers/placement/titles/punishments/finance/military/education, each module containing 'pathology diagnosis→institutional prescription→operational details→fault tolerance' four-segment standard structure, providing first implementable institutional blueprint for modern Chinese constitutional enlightenment; founded 'historiography is politics, evidential research is critique' Donglin-Zhejiang school methodology, influencing Zhang Xuecheng/Wei Yuan/Gong Zizhen/Huang Zongxi/Wang Fuzhi/Wan Sitong/Quan Zuwang/Huang Zonghui/Huang Baijia evidential historiography/institutional engineering dual lineage irreplaceably."
    },
    # H-218: 黄宗羲
    {
        "code": "H-HZX-218",
        "name_zh": "黄宗羲：《明夷待访录》/天下为主君为客/学校即政论/考据史学/东林党魁",
        "name_en": "Huang Zongxi: Mingyi Daifanglu/World as Master Ruler as Guest/School Is Political Discourse/Evidential Historiography/Donglin Party Leader",
        "desc_zh": "明清之际思想家，制度工程/宪政蓝图/证据政治源头。构建「天下为主、君为客」政治本体论革命，将「君主专制=天下大害」显性化为可批判的制度缺陷，设计「宰相制/学校即政论/律令定于一尊」三大制度工程替代方案，完成从「德治祈望」到「制度工程」的范式跃迁。",
        "desc_en": "Ming-Qing transition thinker, source of institutional engineering/constitutional blueprint/evidence politics. Constructed 'world as master, ruler as guest' political ontological revolution, made 'monarchical autocracy = world's great harm' explicit as criticizable institutional defect, designed 'prime minister system/school is political discourse/laws established by one sovereign' three major institutional engineering alternatives, completing paradigm leap from 'virtue governance hope' to 'institutional engineering'.",
        "modes": [42, 34, 32, 36, 25],
        "reason_zh": "黄宗羲《明夷待访录》为中国近代首部系统化宪政蓝图，提供「纲领×建党×建军×建国」完整工程闭环的古典范式。",
        "reason_en": "Huang Zongxi's 'Mingyi Daifanglu' is China's first systematic constitutional blueprint, providing classical paradigm of complete engineering closure: 'platform×party building×army building×nation building'.",
        "steps_zh": ["本体锚定：锁定「君主专制=私天下=天下大害」为明清转型期根本矛盾，确立「天下为主、君为客、臣为役」三元本体论", "协议标准化：设计「宰相制」替代「皇帝亲政」——宰相由「公卿大夫士庶人共推」产出，掌四大实权，受四重监督，行绩效合同", "系统集成：构建「律令定于一尊」立法标准化协议——五阶段立法流程，每条律令含五要素，消除非标准化权力介入", "工程化传承：确立「学校即政论」人才生产-选拔-部署一体化流水线，用「笨功夫」代际复利生产专业治理人才", "动态校准：建立「博征广引、互证参校」证据链验证标准——治史即治国：四源证据→交叉验证→抽象四类规律→编入对应模块→定期复核"],
        "steps_en": ["Ontological Anchoring: Lock 'monarchical autocracy=private world=world great harm' as Ming-Qing transition root contradiction, establish 'world as master, ruler as guest, minister as servant' tripartite ontology", "Protocol Standardization: Design 'prime minister system' replacing 'emperor personal rule'—prime minister produced by 'public nobles officials scholars commoners joint recommendation', holds four real powers, receives four-fold supervision, implements performance contract", "System Integration: Construct 'laws established by one sovereign' legislative standardization protocol—five-stage legislative process, each law contains five elements, eliminate non-standardized power intervention", "Engineering Transmission: Establish 'school is political discourse' talent production-selection-deployment integrated pipeline, use 'pen gong fu' intergenerational compound interest produce professional governance talent", "Dynamic Calibration: Establish 'extensive citation, mutual verification' evidence chain verification standard—historiography is governance: four-source evidence→cross verification→abstract four pattern types→enter corresponding module→periodic review"],
        "expected_zh": "提供中国近代首部系统化宪政蓝图，完成从德治祈望到制度工程的范式跃迁",
        "expected_en": "Provide China's first systematic constitutional blueprint, complete paradigm leap from virtue governance hope to institutional engineering",
        "case_zh": "著《明夷待访录》二十一篇建立八大制度重构模块，每模块含「病理诊断→制度处方→操作细则→容错预案」四段式标准结构，为中国近代宪政启蒙提供首个可落地的制度蓝图；创立「史学即政治、考据即批判」东林-浙东学派方法论，将「博征广引、互证参校」考据技术转化为制度设计的证据链标准，使「治史」直接服务「治国」——清初思想启蒙双峰（黄/顾/王）之首，中国近代「制度工程/宪政蓝图/证据政治」源头。",
        "case_en": "Authored 'Mingyi Daifanglu' twenty-one chapters establishing eight major institutional reconstruction modules, each module containing 'pathology diagnosis→institutional prescription→operational details→fault tolerance' four-segment standard structure, providing first implementable institutional blueprint for modern Chinese constitutional enlightenment; founded 'historiography is politics, evidential research is critique' Donglin-Zhejiang school methodology, transformed 'extensive citation, mutual verification' evidential technique into evidence chain standard for institutional design, made 'historiography' directly serve 'governance'—first of early Qing intellectual enlightenment twin peaks (Huang/Gu/Wang), source of modern Chinese 'institutional engineering/constitutional blueprint/evidence politics'."
    },
    # H-219: 王夫之
    {
        "code": "H-WFZ-219",
        "name_zh": "王夫之：读通鉴论/历史循环/气一元/实学/船山",
        "name_en": "Wang Fuzhi: Reading Tongjian Lun/Historical Cycle/Qi Monism/Real Learning/Chuanshan",
        "desc_zh": "明清之际思想家，史学循环律/实学巨擘双重范式。构建「气一元」单一本体论宇宙发生学，以「历史循环律」重构史学方法论，以「实学」回应晚明空疏，其「气参数空间/历史循环律/实学工程」三维融合，成清初实学/史学/本体论三系血脉共同源头。",
        "desc_en": "Ming-Qing transition thinker, dual paradigm of historiography cycle law/real learning giant. Constructed 'qi monism' single ontological cosmogenesis, reconstructed historiography methodology with 'historical cycle law', responded to late Ming emptiness with 'real learning', their 'qi parameter space/historical cycle law/real learning engineering' three-dimensional fusion became early Qing real learning/historiography/ontology three-lineage common origin.",
        "modes": [22, 25, 37, 1, 35],
        "reason_zh": "王夫之以「气一元」本体论重构宇宙发生学，以「历史循环律」重构史学方法论，以「实学」回应晚明空疏，其「气参数空间/历史循环律/实学工程」三维融合，成清初实学/史学/本体论三系血脉共同源头。",
        "reason_en": "Wang Fuzhi reconstructed cosmogenesis with 'qi monism' ontology, reconstructed historiography methodology with 'historical cycle law', responded to late Ming emptiness with 'real learning', their 'qi parameter space/historical cycle law/real learning engineering' three-dimensional fusion became early Qing real learning/historiography/ontology three-lineage common origin.",
        "steps_zh": ["本体锚定：确立「太虚即气」单一本体——拒绝一切二元论预设，将天地万物/人伦道德/鬼神灵异统一还原为「气之聚散缓急清浊动静」单一物理过程", "协议标准化：提炼「气聚→成形、气散→归无、缓则清轻上浮、急则浊重下沉」四大通用演化算子，用单一数学结构统摄全领域现象", "系统集成：设计「博学/审问/慎思/明辨/笃行」五阶段认知-行动闭环，以「格物穷理」为认知入口，「主静」为心态锚点，「立人极」为行动输出", "工程化传承：识别佛老虚无/词章腐儒/功利科举三大矛盾，锁定「气学本体+伦理工程」为破解组合拳，建立关学双轨并行传承体系", "动态校准：提出「圣人定之以中正仁义而主静」动态调参协议，将道德修养重构为宇宙演化的主动控制工程"],
        "steps_en": ["Ontological Anchoring: Establish 'taixu is qi' single ontology—reject all dualist presets, unify heaven-earth all things/human ethics/spirit anomalies into 'qi gathering-dispersing/slow-fast/clear-turbid-movement-stillness' single physical process", "Protocol Standardization: Extract 'qi gathering→formation, qi dispersing→return void, slow then clear-light-upward-float, fast then turbid-heavy-downward-sink' four universal evolution operators, govern all-domain phenomena with single mathematical structure", "System Integration: Design 'broad learning/careful questioning/cautious thinking/clear discernment/earnest practice' five-stage cognitive-action closure, take 'investigate things exhaust principles' as cognitive entry, 'master stillness' as mindset anchor, 'establish human extreme' as action output", "Engineering Transmission: Identify Buddhism-Daoist void/corrupt literary Confucians/utilitarian exams three contradictions, lock 'qi ontology + ethical engineering' as breakthrough combination, establish Guan Learning dual-track parallel transmission system", "Dynamic Calibration: Propose 'sage determines with impartiality-benevolence-righteousness while mastering stillness' dynamic parameter adjustment protocol, reconstruct moral cultivation as cosmic evolution active control engineering"],
        "expected_zh": "成清初实学/史学/本体论三系血脉共同源头，为历史学引入结构性/规律性/可干预性科学范式",
        "expected_en": "Become early Qing real learning/historiography/ontology three-lineage common origin, introduce structural/regular/intervenable scientific paradigm for historiography",
        "case_zh": "著《读通鉴论》三十九篇，以「气一元」本体重构历史演化逻辑，提出「治乱循环/兴衰规律/民心向背/制度成败」四维历史模型，破「天命/周期/宿命」宿命论，为历史学引入「结构性/规律性/可干预性」科学范式。《张子正蒙注》确立「太虚即气/气聚成形/气散归无」单一本体论，《西铭》注确立「民吾同胞/物吾与也」伦理本体论。其「单一气本体/历史循环律/实学工程/伦理本体」四维融合，成清初实学/史学/本体论三系血脉共同源头，影响戴震/章学诚/张惠言/黄宗会/黄百家/魏源/龚自珍/康有为/梁启超/谭嗣同/张之洞/张謇/严复/蔡元培/胡适/冯友兰/熊十力/牟宗三/唐君毅/徐复观/方以智/李贽等。",
        "case_en": "Authored 'Reading Tongjian Lun' thirty-nine chapters, reconstructed historical evolution logic with 'qi monism' ontology, proposed 'order-chaos cycle/rise-fall patterns/people's hearts orientation/institutional success-failure' four-dimensional historical model, broke 'mandate of heaven/cycle/fatalism' fatalism, introduced 'structural/regular/intervenable' scientific paradigm for historiography. 'Zhangzi Zhengmeng Zhu' established 'taixu is qi/qi gathering forms/qi dispersing returns void' single ontology, 'Ximing Zhu' established 'people my fellow beings/things my companions' ethical ontology. Their 'single qi ontology/historical cycle law/real learning engineering/ethical ontology' four-dimensional fusion became early Qing real learning/historiography/ontology three-lineage common origin, influencing Dai Zhen/Zhang Xuecheng/Zhang Huayan/Huang Zonghui/Huang Baijia/Wei Yuan/Gong Zizhen/Kang Youwei/Liang Qichao/Tan Sitong/Zhang Zhidong/Zhang Jian/Yan Fu/Cai Yuanpei/Hu Shi/Feng Youlan/Xiong Shili/Mou Zongsan/Tang Junyi/Xu Fuguan/Fang Yizhi/Li Zhi etc."
    },
    # H-220: 戴震
    {
        "code": "H-DZ-220",
        "name_zh": "戴震：考据实学/气论/科学精神/衡山/戴东原",
        "name_en": "Dai Zhen: Evidential Real Learning/Qi Theory/Scientific Spirit/Hengshan/Dai Dongyuan",
        "desc_zh": "清代学者，考据实学/科学精神先驱。以「气」为本体重构儒学本体论，以「求真/证经/辨伪」三级验证协议重塑考据方法论，将「性即气质」本体论转化为可操作的「博征广引、互证参校」证据链标准，使「治学」直接服务「治国」——清初实学/考据/科学精神先驱。",
        "desc_en": "Qing scholar, pioneer of evidential real learning/scientific spirit. Reconstructed Confucian ontology with 'qi' as ontology, reshaped evidential methodology with 'seek truth/verify classics/distinguish false' three-level verification protocol, transformed 'nature is qi-zhi' ontology into operable 'extensive citation, mutual verification' evidence chain standard, made 'scholarship' directly serve 'governance'—early Qing real learning/evidential research/scientific spirit pioneer.",
        "modes": [5, 22, 25, 28, 35],
        "reason_zh": "戴震以「气」为本体重构儒学本体论，以「求真/证经/辨伪」三级验证协议重塑考据方法论，将「性即气质」本体论转化为可操作的「博征广引、互证参校」证据链标准，使「治学」直接服务「治国」——清初实学/考据/科学精神先驱。",
        "reason_en": "Dai Zhen reconstructed Confucian ontology with 'qi' as ontology, reshaped evidential methodology with 'seek truth/verify classics/distinguish false' three-level verification protocol, transformed 'nature is qi-zhi' ontology into operable 'extensive citation, mutual verification' evidence chain standard, made 'scholarship' directly serve 'governance'—early Qing real learning/evidential research/scientific spirit pioneer.",
        "steps_zh": ["本体锚定：确立「性即气质」单一本体——拒绝性/气/理/心/物多元论，将人性/物性/道德/物理统一还原为气之聚散/缓急/清浊/动静单一物理过程", "协议标准化：建立「事核而后论、论核而后信」三级验证协议——现象观测→理性推理→实证复核，系统拆解天人感应/五行相生/鬼神报应/谶纬谶语四大迷信体系", "系统集成：确立「天地合气、自然而已」本体论——「天不为人生物、天不为人而变」，将自然律确立为最高裁判权，完成从神学主权到自然主权的管辖权移交", "工程化传承：将验证通过的反迷信结论编码为标准化知识单元，形成可复用/可传播/可迭代的批判性思维工具包", "动态校准：设计「反事实检索协议」——系统性收集违背预期的反例，用负向证据密度量化假设可信度，打破确认偏误自我强化回路"],
        "steps_en": ["Ontological Anchoring: Establish 'nature is qi-zhi' single ontology—reject nature/qi/li/heart/matter pluralism, unify human nature/thing nature/morality/physics into qi gathering-dispersing/slow-fast/clear-turbid/movement-stillness single physical process", "Protocol Standardization: Establish 'matter verified then discuss, argument verified then believe' three-level verification protocol—phenomenon observation→rational reasoning→empirical re-verification, systematically dismantle heaven-human induction/five elements mutual generation/spirit retribution/chenwei prophecy four superstition systems", "System Integration: Establish 'heaven-earth merge qi, natural only' ontology—'heaven not for people produce things, heaven not for people change', establish natural law as highest jurisdiction, complete jurisdiction transfer from theological sovereignty to natural sovereignty", "Engineering Transmission: Encode verification-passed anti-superstition conclusions as standardized knowledge units, form reusable/transmissible/iteratable critical thinking toolkit", "Dynamic Calibration: Design 'counterfactual retrieval protocol'—systematically collect expectation-violating counterexamples, quantify hypothesis credibility with negative evidence density, break confirmation bias self-reinforcement loop"],
        "expected_zh": "为中国早期科学精神奠基，将迷信重构为待验证假设，将权威降级为需复核来源",
        "expected_en": "Lay foundation for early Chinese scientific spirit, reconstruct superstition as hypotheses-to-be-verified, demote authority as sources-needing-re-verification",
        "case_zh": "著《孟子字义疏证》《庄子崇疏》《原善》等。核心：「性即气质」、「求真/证经/辨伪」三级验证。破天人感应：灾异非天谴乃气候周期；破鬼神报应：死则气散鬼神无知；破谶纬预言：事后诸葛亮统计伪造；破五行相生：物质转化非道德因果。建立事核而后论论核而后信三级验证协议，系统拆解天人感应五行相生鬼神报应谶纬谶语四大迷信体系，确立天地合气自然而已自然主义本体论，为中国早期科学精神奠基。",
        "case_en": "Authored 'Mengzi Ziyi Shuzheng', 'Zhuangzi Chongshu', 'Yuanshan' etc. Core: 'nature is qi-zhi', 'seek truth/verify classics/distinguish false' three-level verification. Broke heaven-human induction: disasters not heaven's punishment but climate cycles; broke spirit retribution: death then qi disperses spirits unknowing; broke chenwei prophecy: hindsight statistical forgery; broke five elements mutual generation: material transformation not moral causality. Established matter-verified-then-discuss argument-verified-then-believe three-level verification protocol, systematically dismantled heaven-human induction/five elements mutual generation/spirit retribution/chenwei prophecy four superstition systems, established heaven-earth merge qi natural-only naturalistic ontology, laid foundation for early Chinese scientific spirit."
    },
    # H-221: 墨子
    {
        "code": "H-MZ-221",
        "name_zh": "墨子：兼爱/非攻/墨经逻辑/功利主义/早期科学/防御工程",
        "name_en": "Mozi: Universal Love/Non-Aggression/Mojing Logic/Utilitarianism/Early Science/Defensive Engineering",
        "desc_zh": "战国哲学家，中国早期科学方法论集大成者。构建「兼爱-非攻-墨经」三位一体工程化和平体系：以「兼爱」为目标函数、「非攻」为约束条件、「墨经」为技术标准库；组建「墨家机关」作为世界首个「工程师+士兵+伦理学家」复合型专业组织，标准化守城全链路SOP；《墨经》确立十六大逻辑-几何-力学-光学基础概念，完成从哲学命题到科学定义的范式跃迁。",
        "desc_en": "Warring States philosopher, synthesizer of early Chinese scientific methodology. Constructed 'universal love-non-aggression-Mojing' trinity engineering peace system: 'universal love' as objective function, 'non-aggression' as constraint, 'Mojing' as technical standard library; organized 'Mohism mechanism' as world's first 'engineer+soldier+ethicist' composite professional organization, standardized full defense SOP; 'Mojing' established sixteen logic-geometry-mechanics-optics foundational concepts, completing paradigm leap from philosophical propositions to scientific definitions.",
        "modes": [6, 19, 20, 24, 35],
        "reason_zh": "墨子构建「兼爱-非攻-墨经」三位一体工程化和平体系：以「兼爱」为目标函数、「非攻」为约束条件、「墨经」为技术标准库，将「天下兼相利则治、交相害则乱」转化为可计算的社会福利优化问题；组建「墨家机关」标准化守城全链路SOP；《墨经》确立十六大逻辑-几何-力学-光学基础概念，完成从哲学命题到科学定义的范式跃迁——中国早期科学方法论集大成者。",
        "reason_en": "Mozi constructed 'universal love-non-aggression-Mojing' trinity engineering peace system: 'universal love' as objective function, 'non-aggression' as constraint, 'Mojing' as technical standard library, transformed 'world universal mutual benefit then order, mutual harm then chaos' into calculable social welfare optimization; organized 'Mohism mechanism' standardizing full defense SOP; 'Mojing' established sixteen logic-geometry-mechanics-optics foundational concepts, completing paradigm leap from philosophical propositions to scientific definitions—synthesizer of early Chinese scientific methodology.",
        "steps_zh": ["本体锚定：识别「强凌弱/众暴寡/知诈愚/勇陵怯/恶务加于良」为战国乱世主要矛盾，锁定「兼相利」为破解杠杆，将「爱」重构为无差等普遍", "协议标准化：确立「利天下、兼相利」为边际收益最大化准则，拒绝边际收益为负的仪式性消耗，资源精准配置到生存底线与防御红线", "系统集成：设计「非攻」为纳什均衡策略——墨家机关作为「可信承诺装置」部署于弱国，内化为强国博弈矩阵中的劝阻约束", "工程化传承：建立「平时研器械练战术、战时守城救天下」双态组织模式，用守城实战作为间断均衡选择压力，倒逼《墨经》标准库持续迭代", "动态校准：墨家机关「耕者余食、工者余作、君子有不得已而为之」三重生存底线，拒绝主动出击/只守不攻/救人不图利，实现两百年跨朝代存续组织级抗脆弱性"],
        "steps_en": ["Ontological Anchoring: Identify 'strong bully weak/many oppress few/knowledge deceives ignorance/brave oppress timid/evil adds to good' as Warring States chaos main contradiction, lock 'mutual benefit' as breakthrough lever, reconstruct 'love' as non-differential universal", "Protocol Standardization: Establish 'benefit world, universal mutual benefit' as marginal benefit maximization criterion, reject negative-marginal-benefit ritualistic consumption, precisely allocate resources to survival baseline and defense redline", "System Integration: Design 'non-aggression' as Nash equilibrium strategy—Mohism mechanism as 'credible commitment device' deployed in weak states, internalized as strong state game matrix deterrent constraint", "Engineering Transmission: Establish 'peacetime research weapons drill tactics, wartime defend city save world' dual-state organizational model, use city defense combat as punctuated equilibrium selection pressure, drive Mojing standard library continuous iteration", "Dynamic Calibration: Mohism mechanism 'farmers surplus food, workers surplus labor, gentleman no choice but do' three survival baselines, reject proactive attack/only defend not attack/save people not for profit, achieve two-century cross-dynasty organizational antifragility"],
        "expected_zh": "成中国早期实验科学/工程技术/技术标准化奠基工程，影响张衡/沈括/郭守敬/宋应星/徐光启/李时珍/朱载堉/华罗庚/钱学森/竺可桢科学工程化传统全版图",
        "expected_en": "Become Chinese early experimental science/engineering technology/technical standardization founding engineering, influencing Zhang Heng/Shen Kuo/Guo Shoujing/Song Yingxing/Xu Guangqi/Li Shizhen/Zhu Zaiyu/Hua Luogeng/Qian Xuesen/Zhu Kezhen scientific engineering tradition entire map",
        "case_zh": "著《墨经》「小取/经/说/大取」四编，系统定义十六大核心概念，建立「定义/公理/定理/推理/实验/验证」六步理论体系。实测「小孔成像/凸透镜聚焦/杠杆原理/滑轮组/齿轮传动/弹簧弹性/弓弩机械/云梯攻城/测量仪器」十大实验，建「假设/实验/测量/计算/验证/标准化」六步实验范式。创「墨家机关/攻城器/防御工事/测量仪器」四大工程化交付物。核心填补：模式20「博弈论思维」当前9人覆盖（低频），墨子「非攻=纳什均衡」为中国最早博弈论工程化实践；模式24「间断均衡法」当前10人覆盖（临界低频），墨家「平时练兵-战时救援」双态模式为教科书级案例。",
        "case_en": "Authored 'Mojing' 'Xiaoqu/Jing/Shuo/Daqu' four chapters, systematically defined sixteen core concepts, established 'definition/axiom/theorem/reasoning/experiment/verification' six-step theory system. Empirically tested 'pinhole imaging/convex lens focusing/lever principle/pulley system/gear transmission/spring elasticity/crossbow mechanics/cloud ladder siege/surveying instruments' ten major experiments, built 'hypothesis/experiment/measurement/calculation/verification/standardization' six-step experimental paradigm. Created 'Mohism mechanism/siege weapons/defensive works/surveying instruments' four engineering deliverables. Core fill: mode 20 'game theory thinking' currently 9 people coverage (low frequency), Mozi 'non-aggression=Nash equilibrium' as China's earliest game theory engineering practice; mode 24 'punctuated equilibrium' currently 10 people coverage (critical low frequency), Mohism 'peacetime drill-wartime rescue' dual-state model as textbook-level case."
    },
    # H-222: 曾子
    {
        "code": "H-ZZ-222",
        "name_zh": "曾子：工夫论/三省吾身/孝道/大学传承/君子人格践行",
        "name_en": "Zengzi: Cultivation Theory/Thrice Daily Self-Examination/Filial Piety/Great Learning Transmission/Gentleman Personality Practice",
        "desc_zh": "西汉儒家，儒家工夫论/自主修养工程范式奠基人。创立「工夫论」将道德修养工程化，以「吾日三省吾身」为核心算子，三条审计线覆盖职业责信-社交契约-知识传承三大维度；传承《大学》八目工程链，确立「孝弟」为仁之本的行为级入口协议，将「君子人格」重构为可标准化/可考核/可规模复制的「合格君子」生产规范。",
        "desc_en": "Western Han Confucian, founder of Confucian cultivation theory/autonomous self-cultivation engineering paradigm. Founded 'cultivation theory' engineering moral cultivation, with 'thrice daily examine self' as core operator, three audit lines covering professional loyalty-social contract-knowledge transmission three dimensions; transmitted 'Great Learning' eight-objective engineering chain, established 'filial piety fraternal duty' as benevolence root behavioral entry protocol, reconstructed 'gentleman personality' from ideal type into standardizable/assessable/scalable 'qualified gentleman' production standard.",
        "modes": [9, 36, 37, 28, 35],
        "reason_zh": "曾子以「工夫论」将儒家道德修养工程化，确立「吾日三省吾身」为标准化自省协议，传承《大学》八目工程链，确立「孝弟」为仁之本的行为级入口协议，将「君子人格」从理想型重构为可标准化、可考核、可规模复制的「合格君子」生产规范，成儒家从「说教」走向「工程」的关键转折节点。",
        "reason_en": "Zengzi engineered Confucian moral cultivation with 'cultivation theory', established 'thrice daily examine self' as standardized self-examination protocol, transmitted 'Great Learning' eight-objective engineering chain, established 'filial piety fraternal duty' as benevolence root behavioral entry protocol, reconstructed 'gentleman personality' from ideal type into standardizable/assessable/scalable 'qualified gentleman' production standard, becoming Confucianism's key turning point from 'preaching' to 'engineering'.",
        "steps_zh": ["本体锚定：锁定「外求不如内省、他律不如自律」为修养主要矛盾，确立「自主践履」为破解路径——「学者不患无术，患不自强」", "协议标准化：将「三省吾身」工程化为「日更制度→复盘闭环→负面清单→传承文档」标准动作，用笨功夫复利效应将微小日改累积为人格重构", "系统集成：构建「孝弟→忠信→博爱→亲仁→学文」五层递进修养栈，以最可操作的「事亲从、兄长顺」为入口，层层外扩至零损耗传导", "工程化传承：建立「师承-文本-共同体-仪式」四重冗余传承架构：师承曾子→《大学》文本定型→孔门七十子共同体互证→乡饮酒/释奠仪式仪式化固化", "动态校准：设计「诚意正心」为内核的自适应调参机制——「毋自欺也」：每次三省发现不忠/不信/不习即触发诚意→正心→行为修正，将道德风险控制在单日单省单改微观颗粒度"],
        "steps_en": ["Ontological Anchoring: Lock 'external seeking inferior to internal examination, heteronomy inferior to autonomy' as cultivation main contradiction, establish 'autonomous practice' as breakthrough path—'scholar fears not lack of method, fears not self-strengthening'", "Protocol Standardization: Engineer 'thrice daily examine self' into 'daily update system→review closure→negative list→transmission documentation' standard actions, use pen-gong-fu compound interest accumulate micro daily improvements into personality reconstruction", "System Integration: Construct 'filial-fraternal→loyalty-trust→universal love→befriend ren→study literature' five-layer progressive cultivation stack, most operable 'serve parents obey, elder brothers comply' as entry, layer-by-layer expand to zero-loss conduction", "Engineering Transmission: Establish 'master-disciple transmission-text fixation-community mutual verification-ritual solidification' four-fold redundant transmission architecture: Zengzi transmission→Great Learning text fixation→Confucius seventy disciples community mutual verification→village drinking/ritual ceremony ritual solidification", "Dynamic Calibration: Design 'make sincere rectify heart' as core adaptive parameter adjustment mechanism—'no self-deception': each thrice-examination discovery of disloyal/untruthful/unstudied triggers make sincere→rectify heart→behavior correction, control moral risk at single-day single-examination single-correction micro-granularity"],
        "expected_zh": "成儒家从说教走向工程的关键转折节点，建立可标准化/可考核/可规模复制的合格君子生产规范",
        "expected_en": "Become Confucianism's key turning point from preaching to engineering, establish standardizable/assessable/scalable qualified gentleman production standard",
        "case_zh": "著《孝经》、传《大学》，核心：「吾日三省吾身：为人谋而不忠乎？与朋友交而不信乎？传不习乎？」三条固定审计线覆盖职业责信/社交契约/知识传承。传《大学》「格物致知/诚意正心/修身齐家治国平天下」八目工程链，确立「孝弟」为仁之本的行为级入口协议。其「工夫论/三省/孝道/大学/师承」五维融合，成儒家从「说教」走向「工程」关键转折节点。",
        "case_en": "Authored 'Xiaojing', transmitted 'Daxue', core: 'thrice daily examine self: for others plan not loyal? with friends interact not trust? transmit not practice?' three fixed audit lines covering professional loyalty/social contract/knowledge transmission. Transmitted 'Great Learning' 'investigate things extend knowledge/make sincere rectify heart/cultivate self regulate family govern state pacify world' eight-objective engineering chain, established 'filial piety fraternal duty' as benevolence root behavioral entry protocol. Their 'cultivation theory/thrice examine/filial piety/great learning/master-disciple' five-dimensional fusion became Confucianism's key turning point from 'preaching' to 'engineering'."
    },
    # H-223: 墨子后学技术派
    {
        "code": "H-MZHT-223",
        "name_zh": "墨子后学技术派：墨翟弟子再传/实验科学/技术标准化/工程技术奠基",
        "name_en": "Post-Mozi Technical School: Mozi Disciples Retransmission/Experimental Science/Technical Standardization/Engineering Technology Foundation",
        "desc_zh": "战国墨家再传弟子群体，中国古代实验科学/工程技术/技术标准化奠基工程。在墨家理论基础上，以「实验/标准化/工程化/量化」四重推进：《墨经》四编系统记载五十余核心概念，建立六步理论体系与六步实验范式；实测十大物理/工程实验，建假设-实验-测量-计算-验证-标准化六步实验科学范式；创四大工程化交付物。其「定义/公理/定理/实验/标准化」五步法成中国古代实验科学奠基工程。",
        "desc_en": "Warring States Mohist later disciples collective, founding engineering of Chinese ancient experimental science/engineering technology/technical standardization. On Mohist theoretical foundation, advanced with 'experiment/standardization/engineering/quantification' four-fold: 'Mojing' four chapters systematically recorded fifty-plus core concepts, established six-step theory system and six-step experimental paradigm; empirically tested ten physics/engineering experiments, built hypothesis-experiment-measurement-calculation-verification-standardization six-step experimental science paradigm; created four engineering deliverables. Their 'definition/axiom/theorem/experiment/standardization' five-step method became Chinese ancient experimental science founding engineering.",
        "modes": [25, 12, 38, 28, 35],
        "reason_zh": "墨子后学技术派以「定义/公理/定理/实验/标准化」五步法，成中国古代实验科学/工程技术/技术标准化奠基工程，影响张衡/沈括/郭守敬/宋应星/徐光启/李时珍/朱载堉/华罗庚/钱学森/竺可桢科学工程化传统全版图。",
        "reason_en": "Post-Mozi Technical School with 'definition/axiom/theorem/experiment/standardization' five-step method became Chinese ancient experimental science/engineering technology/technical standardization founding engineering, influencing Zhang Heng/Shen Kuo/Guo Shoujing/Song Yingxing/Xu Guangqi/Li Shizhen/Zhu Zaiyu/Hua Luogeng/Qian Xuesen/Zhu Kezhen scientific engineering tradition entire map.",
        "steps_zh": ["抽象归纳法：从《墨经》五十余概念提炼核心概念簇，生成几何/光学/力学理论框架", "系统思维法：构建六步理论体系与六步实验范式双轨并行", "摸石头过河/实验主义：实测十大实验，建实验科学范式", "制度化制衡：推动《墨经》四编成标准化教材，以文本固化技术防失传", "总体性思维：将六系统耦合，形成实验科学/技术标准化/工程技术奠基范式"],
        "steps_en": ["Abstract Inductive Method: Extract core concept clusters from 'Mojing' fifty-plus concepts, generate geometry/optics/mechanics theoretical framework", "Systems Thinking Method: Construct six-step theory system and six-step experimental paradigm dual-track parallel", "Crossing River by Feeling Stones/Experimentalism: Empirically test ten major experiments, build experimental science paradigm", "Institutionalized Checks and Balances: Push 'Mojing' four chapters as standardized textbooks, solidify technology with text prevent loss", "Holistic Thinking: Couple six systems, form experimental science/technical standardization/engineering technology founding paradigm"],
        "expected_zh": "建立中国古代实验科学/技术标准化/工程技术三位一体奠基范式",
        "expected_en": "Establish Chinese ancient experimental science/technical standardization/engineering technology trinity founding paradigm",
        "case_zh": "仅有墨子个人条目，无墨家技术派集体条目。其「定义/公理/定理/实验/标准化」五步法，成中国古代实验科学/工程技术/技术标准化奠基工程，影响张衡/沈括/郭守敬/宋应星/徐光启/李时珍/朱载堉/华罗庚/钱学森/竺可桢科学工程化传统全版图。",
        "case_en": "Only Mozi individual entry exists, no Mohist technical school collective entry. Their 'definition/axiom/theorem/experiment/standardization' five-step method became Chinese ancient experimental science/engineering technology/technical standardization founding engineering, influencing Zhang Heng/Shen Kuo/Guo Shoujing/Song Yingxing/Xu Guangqi/Li Shizhen/Zhu Zaiyu/Hua Luogeng/Qian Xuesen/Zhu Kezhen scientific engineering tradition entire map."
    },
    # H-224: 白圭
    {
        "code": "H-BG-224",
        "name_zh": "白圭：平籴法/粮价调控/早期宏观调控/商业数学/财政工程化先驱",
        "name_en": "Bai Gui: Price Stabilization/Grain Price Regulation/Early Macro Regulation/Commercial Mathematics/Fiscal Engineering Pioneer",
        "desc_zh": "战国商人/政治家，宏观调控/商业数学/财政工程先驱。以「平籴法/逆周期调控/商业数学建模」三重工程：丰年粮贱平籴收购，歉年粮贵散籴抛售，建常平仓/价格上下限四维调控体系；著《白圭》十二篇创「商业数学建模」，以六维商业函数量化决策，二十年致万金成战国奇迹。",
        "desc_en": "Warring States merchant/statesman, macro regulation/commercial mathematics/fiscal engineering pioneer. Three-fold engineering with 'price stabilization/counter-cyclical regulation/commercial mathematical modeling': bumper year grain cheap stabilize-purchase, famine year grain expensive stabilize-sell, built ever-normal granary/price ceiling-floor four-dimensional regulation system; authored 'Bai Gui' twelve chapters creating 'commercial mathematical modeling', six-dimensional commercial function quantified decisions, twenty years amassed ten-thousand-gold Warring States miracle.",
        "modes": [25, 20, 38, 34, 19],
        "reason_zh": "白圭以「平籴法/逆周期调控/商业数学建模」三重工程，成中国古代宏观调控/商业数学/财政工程化奠基工程。",
        "reason_en": "Bai Gui with 'price stabilization/counter-cyclical regulation/commercial mathematical modeling' three-fold engineering became Chinese ancient macro regulation/commercial mathematics/fiscal engineering founding engineering.",
        "steps_zh": ["本体锚定：提炼「逆周期/平抑/储备/调控」核心框架，生成粮价调控四维模型", "系统思维法：构建「收购/储备/抛售/价格」四维动态平衡系统，纳入农民/商人/国家三方利益博弈模型", "摸石头过河/实验主义：二十年致万金商业实验，以六势商业决策模型验证平籴法可行性", "制度化制衡：推平籴法纳入三政体系，建常平仓国家储备体系，成宏观调控/粮价平抑奠基范式", "边际思维：以「投入/产出/周转/利润/风险/杠杆」六维商业函数量化决策，实现边际收益最大化"],
        "steps_en": ["Ontological Anchoring: Extract 'counter-cyclical/stabilize/reserve/regulate' core framework, generate grain price regulation four-dimensional model", "Systems Thinking Method: Construct 'purchase/reserve/sell/price' four-dimensional dynamic balance system, incorporate farmer/merchant/state three-party interest game model", "Crossing River by Feeling Stones/Experimentalism: Twenty years ten-thousand-gold commercial experiment, verify price stabilization feasibility with six-forces commercial decision model", "Institutionalized Checks and Balances: Push price stabilization into three-governance system, build ever-normal granary national reserve system, become macro regulation/grain price stabilization founding paradigm", "Marginal Thinking: Quantify decisions with 'input/output/turnover/profit/risk/leverage' six-dimensional commercial function, achieve marginal benefit maximization"],
        "expected_zh": "成中国古代宏观调控/商业数学/财政工程化奠基工程，常平仓制度延续两千年",
        "expected_en": "Become Chinese ancient macro regulation/commercial mathematics/fiscal engineering founding engineering, ever-normal granary system continued two thousand years",
                        "case_en": "Under Warring States grain price wild fluctuations, farmer-merchant both trapped, state fiscal out of control, Bai Gui counter-cyclically regulated with price stabilization, built ever-normal granary/price ceiling-floor four-dimensional system. Authored 'Bai Gui' twelve chapters creating commercial mathematical modeling, six-dimensional commercial function quantified decisions, twenty years ten-thousand-gold. His price stabilization adopted"
    }
]

print("✅ Added 10 new figures")
