#!/usr/bin/env python3
"""
Batch C: 文学/艺术/美学 12 位
Codes: H-SC-286 through H-TXZ-297
"""
import json

with open('scenarios_zh.json', 'r', encoding='utf-8') as f:
    zh = json.load(f)
with open('scenarios_en.json', 'r', encoding='utf-8') as f:
    en = json.load(f)
with open('code_maps.json', 'r', encoding='utf-8') as f:
    cm = json.load(f)

figures = [
    {
        'code': 'H-SC-286',
        'name_zh': '苏轼：宋诗巅峰/词牌创新/三苏/赤壁赋/人生三境/豁达人生',
        'name_en': 'Su Shi: Song Poetry Peak/Ci Innovation/Three Sus/Red Cliff Rhapsody/Three Life Realms/Open-Minded Life',
        'desc_zh': '北宋大文豪，"三苏"之一，诗词书画全能，创"豪放派"词风，著《前赤壁赋》《后赤壁赋》《念奴娇·赤壁怀古》，一生三起三落(乌台诗案/黄州/惠州/儋州)始终豁达，成中国文人/诗词/人生哲学三维典范。',
        'desc_en': 'Northern Song literary giant, one of "Three Sus", master of poetry/ci/calligraphy/painting, created "heroic abandon" ci style, authored "Former/ Latter Red Cliff Rhapsody" and "Nian Nu Jiao: Reminiscence of Red Cliff", life of three rises and falls (Crow Terrace Poetry Case/Huangzhou/Huizhou/Danzhou) yet always open-minded, becoming Chinese literati/poetry/life philosophy three-dimensional paradigm.',
        'modes': [23, 26, 27, 21, 18],
        'reason_zh': '苏轼以"三苏"文脉传承诗词巅峰，创"豪放派"词风打破婉约垄断，"三起三落"人生践行"人生三境"(王国维语)，诗/词/文/书/画/茶/医/酒全能，成中国文人气象/词风革新/人生豁达三维集大成。',
        'reason_en': 'Su Shi inherited "Three Sus" literary lineage reaching poetry peak, created "heroic abandon" ci style breaking graceful monopoly, "three rises three falls" life embodied "three realms of life" (Wang Guowei), master of poetry/ci/prose/calligraphy/painting/tea/medicine/wine, becoming Chinese literati bearing/ci innovation/life open-mindedness three-dimensional synthesis.',
        'steps_zh': ['文脉传承：苏洵/苏辙/苏轼"三苏"四科及第，家族文脉/家学渊源/兄弟切磋三位一体', '词风革新：创"豪放派"(大江东去/念奴娇/水调歌头)，打破婉约派垄断，词入诗境/词入画境/词入论境', '人生三境：乌台诗案/黄州/惠州/儋州四谪，践行"古今成大事业者，必经过三种境界"', '全能文人：诗(赤壁赋)/词(水调歌头/定风波)/文(石钟山记)/书(黄州寒食帖)/画(枯木怪石)/茶(斗茶记)/医(洗儿/养生)/酒(东坡肉/酒令)八绝', '传承影响：影响黄庭坚/陈师道/辛弃疾/陆游/杨万里/江夔/吴文英/张炎/周密/王沂孙宋元词坛全版图'],
        'steps_en': ['Literary Lineage: Su Xun/Su Zhe/Su Shi "Three Sus" all passed imperial exams, family literary lineage/scholarly tradition/brotherly refinement trinity', 'Ci Style Innovation: Created "heroic abandon" (Great River Flows East/Nian Nu Jiao/Shui Diao Ge Tou), broke graceful monopoly, ci enters poetry/painting/argument realms', 'Three Life Realms: Crow Terrace Poetry Case/Huangzhou/Huizhou/Danzhou four exiles, embodied "ancient and modern great achievers must pass three realms"', 'Omniscient Literatus: Poetry (Red Cliff Rhapsody)/Ci (Shui Diao Ge Tou/Ding Feng Bo)/Prose (Stone Bell Mountain Record)/Calligraphy (Huangzhou Cold Food Scroll)/Painting (Withered Tree Strange Rocks)/Tea (Tea Contest Record)/Medicine (Washing Children/Health Preservation)/Wine (Dongpo Pork/Wine Games) eight masteries', 'Transmission Influence: Influenced Huang Tingjian/Chen Shidao/Xin Qiji/Lu You/Yang Wanli/Jiang Kui/Wu Wenying/Zhang Yan/Zhou Mi/Wang Yisun Song-Yuan ci world entire map'],
        'expected_zh': '成中国文人气象/词风革新/人生豁达三维集大成，千古词人第一/三苏文脉/人生导师',
        'expected_en': 'Become Chinese literati bearing/ci innovation/life open-mindedness three-dimensional synthesis, greatest ci poet of all ages/Three Sus lineage/life mentor',
        'case_zh': '1036-1101年，字子瞻，号东坡居士。三谪黄州/惠州/儋州，作《定风波·莫听穿林打叶声》《水调歌头·明月几时有》《前后赤壁赋》"横看成岭侧成峰，远近高低各不同"成中国文人气象/豁达人生/词风革新三维教科书。影响黄庭坚/辛弃疾/陆游/江夔/姜夔/王沂孙全版图。',
        'case_en': '1036-1101, courtesy Zizhan, style Dongpo Jushi. Three exiles to Huangzhou/Huizhou/Danzhou, wrote "Ding Feng Bo", "Shui Diao Ge Tou", "Former/Latter Red Cliff Rhapsody". "Viewed horizontally a ridge, vertically a peak" becoming Chinese literati bearing/open-minded life/ci innovation three-dimensional textbook. Influenced Huang Tingjian/Xin Qiji/Lu You/Jiang Kui/Wang Yisun entire map.'
    },
    {
        'code': 'H-HT-287',
        'name_zh': '黄庭坚：江西诗派/一字一金/换骨夺胎/山谷体/苏黄门下',
        'name_en': 'Huang Tingjian: Jiangxi Poetry School/Word Worth Gold/Bone-Changing Soul-Stealing/Shangu Style/Su-Huang Disciples',
        'desc_zh': '北宋诗人，苏轼门下"苏黄"并称，创"江西诗派"，提"换骨夺胎/点铁成金"诗法，著《松风阁诗话》《山谷词》，一字推敲"一字一金"，成中国诗法论/词风/诗派传承三维典范。',
        'desc_en': 'Northern Song poet, disciple of Su Shi, "Su-Huang" paired fame, created "Jiangxi Poetry School", proposed "bone-changing soul-stealing/turning iron to gold" poetic method, authored "Pine Wind Pavilion Poetry Talks" and "Shangu Ci", each word refined "word worth gold", becoming Chinese poetics/ci style/poetry school transmission three-dimensional paradigm.',
        'modes': [23, 24, 25, 26, 18],
        'reason_zh': '黄庭坚以"苏黄"承接苏轼衣钵，创江西诗派确立"换骨夺胎/点铁成金"诗法论，一字推敲"一字一金"，山谷体词风清婉，成中国诗法理论/诗派建设/词风传承三维奠基。',
        'reason_en': 'Huang Tingjian as "Su-Huang" inherited Su Shi mantle, created Jiangxi Poetry School establishing "bone-changing soul-stealing/turning iron to gold" poetics, each word refined "word worth gold", Shangu style ci graceful, becoming Chinese poetics theory/poetry school construction/ci style transmission three-dimensional foundation.',
        'steps_zh': ['诗法论建立："换骨夺胎"改骨架/"点铁成金"改质料，确立前人材料今人炼化的创作论', '江西诗派：以黄庭坚/陈师道/潘大临/洪朋/刘籁/曾几六大家为核心，确立学派体系/传承谱系/创作方法', '一字一金：推敲"僧敲月下门"典故，"两句三年得，一吟双泪流"，极致推敲精神', '词风山谷：清婉/空灵/哲理并重，"清平乐·留人不住醉垂鞭"等代表作传世', '传承谱系：苏轼→黄庭坚→陈师道→杨万里/陆游/范成大/辛弃疾/江夔/吴文英/张炎/周密/王沂孙宋元诗词全版图'],
        'steps_en': ['Poetics Establishment: "Bone-changing" change skeleton/"turning iron to gold" change material, establish creative theory of refining predecessors materials with contemporary craft', 'Jiangxi Poetry School: Core six masters Huang Tingjian/Chen Shidao/Pan Dalin/Hong Peng/Liu Lai/Zeng Ji, establish school system/transmission lineage/creative method', 'Word Worth Gold: Refined "monk knocks moon door" allusion, "two lines three years got, one chant twin tears flow", extreme refinement spirit', 'Ci Style Shangu: Graceful/ethereal/philosophical triad, "Qing Ping Yue - Keep Guest Not Stay Drunk Whip" representative works handed down', 'Transmission Lineage: Su Shi→Huang Tingjian→Chen Shidao→Yang Wanli/Lu You/Fan Chengda/Xin Qiji/Jiang Kui/Wu Wenying/Zhang Yan/Zhou Mi/Wang Yisun Song-Yuan poetry-ci entire map'],
        'expected_zh': '成中国诗法理论/诗派建设/词风传承三维奠基，江西诗派祖师/一字一金/苏黄并称',
        'expected_en': 'Become Chinese poetics theory/poetry school construction/ci style transmission three-dimensional foundation, Jiangxi Poetry School patriarch/word worth gold/Su-Huang paired fame',
        'case_zh': '1045-1105年，字鲁直，号山谷道人。苏轼称"鲁直诗如咳唾珠玑"。创江西诗派，"换骨夺胎/点铁成金"成中国诗法论金科玉律。影响陈师道/杨万里/陆游/范成大/辛弃疾/江夔/吴文英/张炎/周密/王沂孙全版图。',
        'case_en': '1045-1105, courtesy Lüzhi, style Shangu Daoren. Su Shi praised "Luzhi poetry like coughing pearls". Created Jiangxi Poetry School, "bone-changing/turning iron to gold" became Chinese poetics golden rule. Influenced Chen Shidao/Yang Wanli/Lu You/Fan Chengda/Xin Qiji/Jiang Kui/Wu Wenying/Zhang Yan/Zhou Mi/Wang Yisun entire map.'
    },
    {
        'code': 'H-MF-288',
        'name_zh': '米芾：书法四家/米家山水/海岳名言/书史/苏黄米蔡',
        'name_en': 'Mi Fu: Four Calligraphy Masters/Mi Family Landscape/Haiyue Mingyan/Calligraphy History/Su-Huang-Mi-Cai',
        'desc_zh': '北宋书法家/画家/鉴赏家，"宋四家"(苏黄米蔡)之一，创"米点山水/米家山水"，著《海岳名言》《书史》《画史》，书法"布置经营/字势险绝"，成中国书法/绘画/鉴赏/文人气质四维典范。',
        'desc_en': 'Northern Song calligrapher/painter/connoisseur, one of "Four Song Masters" (Su-Huang-Mi-Cai), created "Mi dot landscape/Mi family landscape", authored "Haiyue Mingyan/Calligraphy History/Painting History", calligraphy "composition management/character posture perilous", becoming Chinese calligraphy/painting/connoisseurship/literati temperament four-dimensional paradigm.',
        'modes': [23, 26, 29, 25, 18],
        'reason_zh': '米芾以"苏黄米蔡"书法四家之一，创"米点/米家山水"开文人画新境，著《海岳名言/书史/画史》奠基书画鉴赏学，痴癫书画"拜石为兄"成文人气质极致，成中国书法/绘画/鉴赏/文人气质四维集大成。',
        'reason_en': 'Mi Fu as one of "Su-Huang-Mi-Cai" four calligraphy masters, created "Mi dot/Mi family landscape" opening literati painting new realm, authored "Haiyue Mingyan/Calligraphy History/Painting History" founding calligraphy-painting connoisseurship, obsessive "worship stone as brother" becoming literati temperament extreme, becoming Chinese calligraphy/painting/connoisseurship/literati temperament four-dimensional synthesis.',
        'steps_zh': ['书法四家：苏轼/黄庭坚/米芾/蔡襄"苏黄米蔡"并称，米芾"字势险绝/布置经营"独步天下', '米家山水：创"米点山水/大米点/小米点/焦墨/淡墨"层层叠叠，开文人山水画写意新境', '鉴赏奠基：《海岳名言》记载历代书画真伪/品评/轶事，《书史》《画史》系统梳理历代名迹，奠基中国书画鉴赏学', '痴癫气质："拜石为兄/佩砚而卧/洗砚池成文"痴癫文人气质极致，成中国文人痴/癫/狂/傲/逸五气质典范', '传承版图：影响赵孟頫/文徵明/董其昌/王铎/傅山/康有为/启功/沈鹏/欧阳中石/欧阳询书法/绘画/鉴赏全版图'],
        'steps_en': ['Four Calligraphy Masters: Su Shi/Huang Tingjian/Mi Fu/Cai Xiang "Su-Huang-Mi-Cai" paired fame, Mi Fu "character posture perilous/composition management" unrivaled', 'Mi Family Landscape: Created "Mi dot landscape/large Mi dot/small Mi dot/burnt ink/light ink" layered, opened literati landscape painting freehand new realm', 'Connoisseurship Foundation: "Haiyue Mingyan" records历代 calligraphy-painting authenticity/critique/anecdotes, "Calligraphy History/Painting History" systematically organize历代 masterpieces, founding Chinese calligraphy-painting connoisseurship', 'Obsessive Temperament: "Worship stone as brother/sleep with inkstone/wash inkstone pond becomes text" obsessive literati temperament extreme, becoming Chinese literati obsession/madness/wildness/arrogance/ease five temperaments paradigm', 'Transmission Map: Influenced Zhao Mengfu/Wen Zhengming/Dong Qichang/Wang Duo/Fu Shan/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi/Ouyang Xun calligraphy/painting/connoisseurship entire map'],
        'expected_zh': '成中国书法/绘画/鉴赏/文人气质四维集大成，宋四家之一/米家山水祖师/海岳名言奠基',
        'expected_en': 'Become Chinese calligraphy/painting/connoisseurship/literati temperament four-dimensional synthesis, one of Four Song Masters/Mi Family Landscape patriarch/Haiyue Mingyan foundation',
        'case_zh': '1051-1107年，字元章，号海岳外史。苏轼称"米颠真奇绝"。拜石为兄/佩砚而卧/洗砚池成文。《海岳名言/书史/画史》三大著作奠基鉴赏学。书法"布置经营/字势险绝"成宋四家极致。影响赵孟頫/文徵明/董其昌/王铎/傅山/康有为/启功/沈鹏/欧阳中石全版图。',
        'case_en': '1051-1107, courtesy Yuanzhang, style Haiyue Waishi. Su Shi called "Mi Dian truly marvelous". Worship stone as brother/sleep with inkstone/wash inkstone pond becomes text. Three works Haiyue Mingyan/Calligraphy History/Painting History found connoisseurship. Calligraphy "composition management/character posture perilous" becoming Four Song Masters extreme. Influenced Zhao Mengfu/Wen Zhengming/Dong Qichang/Wang Duo/Fu Shan/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi/Ouyang Xun entire map.'
    },
    {
        'code': 'H-ZMF-289',
        'name_zh': '赵孟頫：元四家/书法大家/赵体/宋克/管道升/书法传承',
        'name_en': 'Zhao Mengfu: Yuan Four Masters/Calligraphy Grandmaster/Zhao Style/Song Ke/Guan Daosheng/Calligraphy Transmission',
        'desc_zh': '元代书法家/画家，"元四家"之首，创"赵体"楷书/行书楷范，"书画同源"论奠基文人画理论，夫人管道升书画双绝，父子/女婿/弟子传承赵体，成中国书法/绘画/理论/家族传承四维典范。',
        'desc_en': 'Yuan calligrapher/painter, first of "Yuan Four Masters", created "Zhao Style" regular/running script model, "calligraphy-painting same origin" theory founded literati painting theory, wife Guan Daosheng calligraphy-painting both mastered, father-son/son-in-law/disciple transmitted Zhao Style, becoming Chinese calligraphy/painting/theory/family transmission four-dimensional paradigm.',
        'modes': [23, 26, 28, 25, 18],
        'reason_zh': '赵孟頫以"书画同源"论奠基文人画理论，创"赵体"楷行楷范成后世楷书正统，元四家之首/书画双绝/家族传承(子雍/女婿柯九思/夫人管道升/弟子柯九思/倪瓒/王蒙/吴镇/黄公望)，成中国书法/绘画/理论/家族传承四维集大成。',
        'reason_en': 'Zhao Mengfu founded literati painting theory with "calligraphy-painting same origin", created "Zhao Style" regular/running script model becoming later regular script orthodoxy, first of Yuan Four Masters/calligraphy-painting dual mastery/family transmission (son Yong/son-in-law Ke Jiusi/wife Guan Daosheng/disciple Ke Jiusi/Ni Zan/Wang Meng/Wu Zhen/Huang Gongwang), becoming Chinese calligraphy/painting/theory/family transmission four-dimensional synthesis.',
        'steps_zh': ['书画同源："书画本同源，异在名与迹"，以书法笔意入画，奠基文人画理论核心', '赵体楷行：楷书圆润/行书飘逸/字法严谨，成明清楷书正统/科举考试楷书范本/后世书法教科书', '元四家之首：赵孟頫/黄公望/王蒙/倪瓒/吴镇"元四家"并称，赵为首/书画双绝/理论奠基', '家族传承：夫人管道升书画双绝/子雍/女婿柯九思/弟子倪瓒/王蒙/吴镇/黄公望，赵体世代相传', '理论奠基：《松雪斋书画题跋》系统阐述书法/绘画/鉴赏/理论，成中国书法理论/文人画理论双奠基'],
        'steps_en': ['Calligraphy-Painting Same Origin: "Calligraphy and painting originally same source, differ only in name and trace", brush intent into painting, founding literati painting theory core', 'Zhao Style Regular-Running: Regular round/running graceful/character law rigorous, becoming Ming-Qing regular orthodoxy/imperial exam regular model/later calligraphy textbook', 'First of Yuan Four Masters: Zhao Mengfu/Huang Gongwang/Wang Meng/Ni Zan/Wu Zhen "Yuan Four Masters" paired fame, Zhao first/calligraphy-painting dual mastery/theory foundation', 'Family Transmission: Wife Guan Daosheng calligraphy-painting dual mastery/son Yong/son-in-law Ke Jiusi/disciple Ni Zan/Wang Meng/Wu Zhen/Huang Gongwang, Zhao Style generationally transmitted', 'Theory Foundation: "Songxue Studio Calligraphy-Painting Inscriptions" systematically expound calligraphy/painting/connoisseurship/theory, becoming Chinese calligraphy theory/literati painting theory dual foundation'],
        'expected_zh': '成中国书法/绘画/理论/家族传承四维集大成，元四家之首/赵体正统/书画同源论奠基',
        'expected_en': 'Become Chinese calligraphy/painting/theory/family transmission four-dimensional synthesis, first of Yuan Four Masters/Zhao Style orthodoxy/calligraphy-painting same origin theory foundation',
        'case_zh': '1254-1322年，字子昂，号松雪道人。"书画同源"论改变中国绘画史。赵体楷书成明清科举正字/楷书正统。夫人管道升墨竹/兰蕙双绝。子雍/女婿柯九思/弟子倪瓒/王蒙/吴镇/黄公望传承赵体。影响文徵明/董其昌/王铎/傅山/康有为/启功/沈鹏/欧阳中石书法/绘画/理论全版图。',
        'case_en': '1254-1322, courtesy Ziang, style Songxue Daoren. "Calligraphy-painting same origin" changed Chinese painting history. Zhao Style regular became Ming-Qing imperial exam standard/regular orthodoxy. Wife Guan Daosheng ink bamboo/orchid dual mastery. Son Yong/son-in-law Ke Jiusi/disciple Ni Zan/Wang Meng/Wu Zhen/Huang Gongwang transmitted Zhao Style. Influenced Wen Zhengming/Dong Qichang/Wang Duo/Fu Shan/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi entire map.'
    },
    {
        'code': 'H-WZM-290',
        'name_zh': '文徵明：明四家/文衡山/衡山体/文氏书画/文嘉/文彭/书画传承',
        'name_en': 'Wen Zhengming: Ming Four Masters/Wen Hengshan/Hengshan Style/Wen Family Calligraphy-Painting/Wen Jia/Wen Peng/Calligraphy-Painting Transmission',
        'desc_zh': '明代书法家/画家，"明四家"(沈周/文徵明/唐寅/仇英)之一，创"衡山体"楷行楷范，"文氏书画"家族三代传承(父文林/子文嘉/文彭/孙文同/弟子王宠/徐渭/陈淳/陆师道/文伯仁)，成中国书法/绘画/家族传承/文人风骨四维典范。',
        'desc_en': 'Ming calligrapher/painter, one of "Ming Four Masters" (Shen Zhou/Wen Zhengming/Tang Yin/Qiu Ying), created "Hengshan Style" regular/running script model, "Wen Family Calligraphy-Painting" family three-generation transmission (father Wen Lin/sons Wen Jia & Wen Peng/grandson Wen Tong/disciples Wang Chong/Xu Wei/Chen Chun/Lu Shidao/Wen Boren), becoming Chinese calligraphy/painting/family transmission/literati integrity four-dimensional paradigm.',
        'modes': [23, 26, 28, 25, 18],
        'reason_zh': '文徵明以"衡山体"楷行楷范成明代书法正统，"文氏书画"家族三代/弟子群传承成书画世家，明四家之二/书画双绝/风骨峻峭/不仕隐逸，成中国书法/绘画/家族传承/文人风骨四维集大成。',
        'reason_en': 'Wen Zhengming with "Hengshan Style" regular/running model became Ming calligraphy orthodoxy, "Wen Family Calligraphy-Painting" three-generation family/disciples group transmitted becoming calligraphy-painting aristocratic family, second of Ming Four Masters/calligraphy-painting dual mastery/integrity lofty/not serving reclusive, becoming Chinese calligraphy/painting/family transmission/literati integrity four-dimensional synthesis.',
        'steps_zh': ['衡山体：楷书方正/行书秀润/小楷极致(《洛神赋》《草堂十志》)，成明代楷书正统/后世小楷范本', '明四家：沈周/文徵明/唐寅/仇英"明四家"并称，文以书法/绘画/理论/传承最全面称雄', '文氏书画：父文林/子文嘉/文彭/孙文同/弟子王宠/徐渭/陈淳/陆师道/文伯仁，三代九人书画世家罕见', '风骨峻峭：不仕为官/隐居衡山/诗书画印四绝/风骨峻峭/不媚权贵，成明代文人风骨典范', '传承版图：影响董其昌/王铎/傅山/王澍/阮元/包世臣/杨守敬/康有为/启功/沈鹏/欧阳中石书法/绘画/理论/传承全版图'],
        'steps_en': ['Hengshan Style: Regular square/running graceful/small regular extreme ("Luo Shen Fu"/"Cao Tang Ten Poems"), became Ming regular orthodoxy/later small regular model', 'Ming Four Masters: Shen Zhou/Wen Zhengming/Tang Yin/Qiu Ying "Ming Four Masters" paired fame, Wen most comprehensive in calligraphy/painting/theory/transmission', 'Wen Family Calligraphy-Painting: Father Wen Lin/sons Wen Jia & Wen Peng/grandson Wen Tong/disciples Wang Chong/Xu Wei/Chen Chun/Lu Shidao/Wen Boren, three generations nine persons calligraphy-painting aristocratic family rare', 'Integrity Lofty: Not serving as official/recluse at Hengshan/poetry-calligraphy-painting-seal four masteries/integrity lofty/not flattering power, becoming Ming literati integrity paradigm', 'Transmission Map: Influenced Dong Qichang/Wang Duo/Fu Shan/Wang Shu/Ruan Yuan/Bao Shichen/Yang Shoujing/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi calligraphy/painting/theory/transmission entire map'],
        'expected_zh': '成中国书法/绘画/家族传承/文人风骨四维集大成，明四家之二/衡山体正统/文氏书画世家/风骨典范',
        'expected_en': 'Become Chinese calligraphy/painting/family transmission/literati integrity four-dimensional synthesis, second of Ming Four Masters/Hengshan Style orthodoxy/Wen Family Calligraphy-Painting aristocratic family/integrity paradigm',
        'case_zh': '1470-1559年，字征明，号衡山居士。"明四家"之二，衡山体楷行楷范。父文林/子文嘉文彭/孙文同/弟子王宠徐渭陈淳陆师道文伯仁，三代九人书画世家。不仕隐居衡山，风骨峻峭。影响董其昌/王铎/傅山/康有为/启功/沈鹏/欧阳中石全版图。',
        'case_en': '1470-1559, courtesy Zhengming, style Hengshan Jushi. Second of "Ming Four Masters", Hengshan Style regular/running model. Father Wen Lin/sons Wen Jia Wen Peng/grandson Wen Tong/disciples Wang Chong/Xu Wei/Chen Chun/Lu Shidao/Wen Boren, three generations nine persons calligraphy-painting aristocratic family. Not serving, recluse at Hengshan, integrity lofty. Influenced Dong Qichang/Wang Duo/Fu Shan/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi entire map.'
    },
    {
        'code': 'H-DQC-291',
        'name_zh': '董其昌：明末清初/南北宗论/董体/书画理论/八大家',
        'name_en': 'Dong Qichang: Late Ming Early Qing/North-South School Theory/Dong Style/Calligraphy-Painting Theory/Eight Masters',
        'desc_zh': '明末清初书法家/画家/理论家，创"南北宗论"分类中国画史(南宗王维/北宗李思训)，创"董体"书法成清初正统，"八大家"(董其昌/王铎/王翚/王时敏/王原祁/石涛/龚贤/恽寿平)并称，成中国画史分期/书法正统/理论体系/流派构建四维典范。',
        'desc_en': 'Late Ming early Qing calligrapher/painter/theorist, created "North-South School Theory" classifying Chinese painting history (South School Wang Wei/North School Li Sixun), created "Dong Style" calligraphy becoming early Qing orthodoxy, "Eight Masters" (Dong Qichang/Wang Duo/Wang Hui/Wang Shimin/Wang Yuanqi/Shitao/Gong Xian/Yun Shouping) paired fame, becoming Chinese painting periodization/calligraphy orthodoxy/theory system/school construction four-dimensional paradigm.',
        'modes': [23, 24, 25, 28, 18],
        'reason_zh': '董其昌以"南北宗论"重构中国画史脉络(南宗文人画/北宗院体画)，"董体"书法成清初康乾楷书正统，"八大家"并称确立流派体系，成中国画史分期/书法正统/理论体系/流派构建四维奠基。',
        'reason_en': 'Dong Qichang reconstructed Chinese painting lineage with "North-South School Theory" (South School literati painting/North School academy painting), "Dong Style" calligraphy became early Qing Kang-Qian regular orthodoxy, "Eight Masters" paired fame establishing school system, becoming Chinese painting periodization/calligraphy orthodoxy/theory system/school construction four-dimensional foundation.',
        'steps_zh': ['南北宗论：借禅宗南北宗分中国画史：南宗王维/董源/巨然/米芾/黄公望/吴镇/倪瓒/王蒙→文人画正统；北宗李思训/李昭道/赵伯驹/马远/夏圭/戴进/仇英→院体画/职业画家', '董体书法：行草飘逸/用笔圆转/结体疏朗，成清初康熙/乾隆/嘉庆三朝楷行正统/科举考试范本/启功/沈鹏/欧阳中石直承', '八大家体系：董其昌/王铎/王翚/王时敏/王原祁/石涛/龚贤/恽寿平"八大家"并称，确立明清画坛流派体系/传承谱系/品评标准', '理论体系：《画禅室随笔》《容台山房集》系统阐述画论/书论/鉴赏/史论，成中国书画理论/鉴赏学/史学三奠基', '传承版图：影响王铎/王翚/王时敏/王原祁/石涛/龚贤/恽寿平/王澍/阮元/包世臣/杨守敬/康有为/启功/沈鹏/欧阳中石书法/绘画/理论/流派全版图'],
        'steps_en': ['North-South School Theory: Borrowed Zen North-South schools to classify Chinese painting: South School Wang Wei/Dong Yuan/Ju Ran/Mi Fu/Huang Gongwang/Wu Zhen/Ni Zan/Wang Meng → literati painting orthodoxy; North School Li Sixun/Li Zhaodao/Zhao Bozu/Ma Yuan/Xia Gui/Dai Jin/Qiu Ying → academy painting/professional painters', 'Dong Style Calligraphy: Running-cursive graceful/brush round/structure sparse, became early Qing Kangxi/Qianlong/Jiaqing three reigns regular-running orthodoxy/imperial exam model/Qi Gong/Shen Peng/Ouyang Zhongshi direct inheritance', 'Eight Masters System: Dong Qichang/Wang Duo/Wang Hui/Wang Shimin/Wang Yuanqi/Shitao/Gong Xian/Yun Shouping "Eight Masters" paired fame, establishing Ming-Qing painting circle school system/transmission lineage/critique standards', 'Theory System: "Huachan Studio Essays"/"Rongtai Mountain House Collection" systematically expound painting theory/calligraphy theory/connoisseurship/history, becoming Chinese calligraphy-painting theory/connoisseurship/history three foundations', 'Transmission Map: Influenced Wang Duo/Wang Hui/Wang Shimin/Wang Yuanqi/Shitao/Gong Xian/Yun Shouping/Wang Shu/Ruan Yuan/Bao Shichen/Yang Shoujing/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi entire map'],
        'expected_zh': '成中国画史分期/书法正统/理论体系/流派构建四维奠基，南北宗论/董体/八大家/理论奠基四大遗产',
        'expected_en': 'Become Chinese painting periodization/calligraphy orthodoxy/theory system/school construction four-dimensional foundation, North-South School/Dong Style/Eight Masters/theory foundation four great legacies',
        'case_zh': '1555-1636年，字玄宰，号香光居士。"南北宗论"重构中国画史，"董体"成清初楷行正统。"八大家"董其昌/王铎/王翚/王时敏/王原祁/石涛/龚贤/恽寿平确立流派体系。影响王铎/王翚/王时敏/王原祁/石涛/龚贤/恽寿平/王澍/阮元/包世臣/康有为/启功/沈鹏/欧阳中石全版图。',
        'case_en': '1555-1636, courtesy Xuanzai, style Xiangguang Jushi. "North-South School Theory" reconstructed Chinese painting history, "Dong Style" became early Qing regular-running orthodoxy. "Eight Masters" Dong Qichang/Wang Duo/Wang Hui/Wang Shimin/Wang Yuanqi/Shitao/Gong Xian/Yun Shouping established school system. Influenced Wang Duo/Wang Hui/Wang Shimin/Wang Yuanqi/Shitao/Gong Xian/Yun Shouping/Wang Shu/Ruan Yuan/Bao Shichen/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi entire map.'
    },
    {
        'code': 'H-WXZ-292',
        'name_zh': '王羲之：书圣/兰亭集序/永字八法/书法正统/王献之/二王/书法传承',
        'name_en': 'Wang Xizhi: Calligraphy Sage/Preface to Orchid Pavilion/Eight Principles of Yong/Calligraphy Orthodoxy/Wang Xianzhi/Two Wangs/Calligraphy Transmission',
        'desc_zh': '东晋书法家，"书圣"，著《兰亭集序》"天下第一行书"，创"永字八法"奠基楷书笔法，父子(王羲之/王献之)"二王"并称，成中国书法/楷书/行书/草书/家族传承/审美标准六维奠基。',
        'desc_en': 'Eastern Jin calligrapher, "Calligraphy Sage", authored "Preface to Orchid Pavilion" "world first running script", created "Eight Principles of Yong" founding regular script brush method, father-son (Wang Xizhi/Wang Xianzhi) "Two Wangs" paired fame, becoming Chinese calligraphy/regular/running/cursive/family transmission/aesthetic standard six-dimensional foundation.',
        'modes': [23, 26, 28, 25, 18],
        'reason_zh': '王羲之以《兰亭集序》"天下第一行书"定行书审美巅峰，"永字八法"(侧/勒/努/趯/策/掠/啄/磔)奠基楷书笔法体系，父子"二王"并称/家族传承/后世临摹正统，成中国书法/楷书/行书/草书/传承/审美六维奠基。',
        'reason_en': 'Wang Xizhi established running script aesthetic peak with "Preface to Orchid Pavilion" "world first running script", "Eight Principles of Yong" (side/press/exert/flick/whip/slash/peck/dot) founded regular script brush method system, father-son "Two Wangs" paired fame/family transmission/later copying orthodoxy, becoming Chinese calligraphy/regular/running/cursive/transmission/aesthetic six-dimensional foundation.',
        'steps_zh': ['兰亭集序：永和九年兰亭修稣，众贤毕至，醉书《兰亭集序》"天下第一行书"，神韵/气韵/笔韵三韵合一', '永字八法："永"字八笔侧/勒/努/趯/策/掠/啄/磔，提炼楷书八大基本笔法，奠基楷书笔法体系/教学标准/临摹范本', '二王传承：父王羲之/子王献之"二王"并称，王献之"大令"/行草/笔法圆转/父子一脉相承/家族书法世家', '审美标准：唐太宗"得王羲之笔意者惟欧阳询"，宋/元/明/清/现代书法家无不临二王，成中国书法审美最高标准', '传承版图：欧阳询/虞世南/褚遂良/薛稷/颜真卿/柳公权/苏轼/黄庭坚/米芾/赵孟頫/文徵明/董其昌/王铎/傅山/康有为/启功/沈鹏/欧阳中石全版图'],
        'steps_en': ['Orchid Pavilion Preface: 9th year of Yonghe Orchid Pavilion gathering, drunk wrote "Preface" "world first running script", spirit/qi/brush three rhythms unity', 'Eight Principles of Yong: "Yong" character eight strokes side/press/exert/flick/whip/slash/peck/dot, extracted regular script eight basic strokes, founding regular script brush system/teaching standard/copying model', 'Two Wangs Transmission: Father Wang Xizhi/son Wang Xianzhi "Two Wangs" paired fame, Wang Xianzhi "Grand Command"/running-cursive/brush round/father-son one lineage/family calligraphy aristocracy', 'Aesthetic Standard: Tang Taizong "only Ouyang Xun got Wang Xizhi brush intent", Song/Yuan/Ming/Qing/modern calligraphers all copy Two Wangs, becoming Chinese calligraphy aesthetic highest standard', 'Transmission Map: Ouyang Xun/Yu Shinan/Chu Suiliang/Xue Ji/Yan Zhenqing/Liu Gongquan/Su Shi/Huang Tingjian/Mi Fu/Zhao Mengfu/Wen Zhengming/Dong Qichang/Wang Duo/Fu Shan/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi entire map'],
        'expected_zh': '成中国书法/楷书/行书/草书/家族传承/审美标准六维奠基，书圣/兰亭/永字八法/二王/传承/审美六大遗产',
        'expected_en': 'Become Chinese calligraphy/regular/running/cursive/family transmission/aesthetic standard six-dimensional foundation, Calligraphy Sage/Orchid Pavilion/Eight Principles/Two Wangs/Transmission/Aesthetic six great legacies',
        'case_zh': '303-361年，字逸少，号丹青居士。永和九年兰亭集序"天下第一行书"。"永字八法"侧勒努趯策掠啄磔。子献之"大令"二王并称。唐太宗痴迷/买兰亭/陪葬昭陵。影响欧阳询/虞世南/褚遂良/薛稷/颜真卿/柳公权/苏轼/黄庭坚/米芾/赵孟頫/文徵明/董其昌/王铎/傅山/康有为/启功/沈鹏/欧阳中石全版图。',
        'case_en': '303-361, courtesy Yishao, style Danqing Jushi. 9th Yonghe Orchid Pavilion Preface "world first running script". "Eight Principles of Yong" side/press/exert/flick/whip/slash/peck/dot. Son Xianzhi "Grand Command" Two Wangs paired. Tang Taizong obsessed/bought Orchid Pavilion/buried with Zhao Mausoleum. Influenced Ouyang Xun/Yu Shinan/Chu Suiliang/Xue Ji/Yan Zhenqing/Liu Gongquan/Su Shi/Huang Tingjian/Mi Fu/Zhao Mengfu/Wen Zhengming/Dong Qichang/Wang Duo/Fu Shan/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi entire map.'
    },
    {
        'code': 'H-YZQ-293',
        'name_zh': '颜真卿：颜体/楷书正统/忠义/颜鲁公/颜体传承/书法风骨',
        'name_en': 'Yan Zhenqing: Yan Style/Regular Orthodoxy/Loyalty/Yan Lu Gong/Yan Style Transmission/Calligraphy Integrity',
        'desc_zh': '唐代书法家，"颜体"楷书正统(颜勤礼碑/多宝塔碑/祭侄文稿)，"颜鲁公"忠义风骨(安史之乱/平原守城/慷慨就义)，成中国楷书/忠义/风骨/书法/传承五维典范。',
        'desc_en': 'Tang calligrapher, "Yan Style" regular script orthodoxy (Yan Qinli Stele/Duobao Pagoda Stele/Nephew Manuscript), "Yan Lu Gong" loyalty integrity (An-Shi Rebellion/defending Pingyuan/righteous martyrdom), becoming Chinese regular script/loyalty/integrity/calligraphy/transmission five-dimensional paradigm.',
        'modes': [23, 26, 28, 25, 18],
        'reason_zh': '颜真卿以"颜体"楷书雄浑/方正/丰满成唐楷正统/后世楷书正统，"颜鲁公"安史之乱守城/祭侄文稿/慷慨就义成忠义风骨典范，成中国楷书/忠义/风骨/书法/传承五维集大成。',
        'reason_en': 'Yan Zhenqing with "Yan Style" regular script masculine/square/full became Tang regular orthodoxy/later regular orthodoxy, "Yan Lu Gong" An-Shi Rebellion defended city/nephew manuscript/righteous martyrdom became loyalty integrity paradigm, becoming Chinese regular script/loyalty/integrity/calligraphy/transmission five-dimensional synthesis.',
        'steps_zh': ['颜体楷书：颜勤礼碑/多宝塔碑/麻姑仙坛记/争座位帖/祭侄文稿，雄浑/方正/丰满/笔力遒劲，成唐楷/后世楷书正统', '忠义风骨：安史之乱起兵/平原守城/李希烈劝降不屈/祭侄文稿"季明早夭"泪洒纸端/慷慨就义，成忠义/风骨/气节典范', '楷书正统：唐太宗"得王羲之笔意者惟欧阳询"，颜真卿"得王羲之笔意者惟颜真卿"，成唐楷四家/后世楷书正统双峰', '风骨传承：颜体→柳公权(颜筋柳骨)→赵孟頫(赵体)→文徵明(衡山体)→董其昌(董体)→康有为/启功/沈鹏/欧阳中石，风骨代代相传', '传承版图：影响柳公权/赵孟頫/文徵明/董其昌/王铎/傅山/康有为/启功/沈鹏/欧阳中石/欧阳询/虞世南/褚遂良/薛稷/颜真卿/柳公权全版图'],
        'steps_en': ['Yan Style Regular: Yan Qinli Stele/Duobao Pagoda Stele/Magu Altar Record/Seat Dispute Post/Nephew Manuscript, masculine/square/full/brush force vigorous, became Tang regular/later regular orthodoxy', 'Loyalty Integrity: An-Shi Rebellion raised troops/defended Pingyuan/Li Xilie persuaded surrender refused/Nephew Manuscript "Ji Ming died young" tears on paper/righteous martyrdom, became loyalty/integrity/integrity paradigm', 'Regular Orthodoxy: Tang Taizond "only Ouyang Xun got Wang Xizhi brush intent", Yan Zhenqing "only Yan Zhenqing got Wang Xizhi brush intent", became Tang Four Masters/later regular orthodoxy twin peaks', 'Integrity Transmission: Yan Style→Liu Gongquan (Yan sinew Liu bone)→Zhao Mengfu (Zhao Style)→Wen Zhengming (Hengshan Style)→Dong Qichang (Dong Style)→Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi, integrity generationally transmitted', 'Transmission Map: Influenced Liu Gongquan/Zhao Mengfu/Wen Zhengming/Dong Qichang/Wang Duo/Fu Shan/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi/Ouyang Xun/Yu Shinan/Chu Suiliang/Xue Ji/Yan Zhenqing/Liu Gongquan entire map'],
        'expected_zh': '成中国楷书/忠义/风骨/书法/传承五维集大成，颜体/颜鲁公/祭侄文稿/风骨传承/楷书正统五大遗产',
        'expected_en': 'Become Chinese regular script/loyalty/integrity/calligraphy/transmission five-dimensional synthesis, Yan Style/Yan Lu Gong/Nephew Manuscript/integrity transmission/regular orthodoxy five great legacies',
        'case_zh': '709-785年，字清臣，号颜鲁公。安史之乱守平原/祭侄文稿/慷慨就义。颜勤礼碑/多宝塔碑/祭侄文稿三大名迹。"颜筋柳骨"成楷书最高评价。影响柳公权/赵孟頫/文徵明/董其昌/王铎/傅山/康有为/启功/沈鹏/欧阳中石全版图。',
        'case_en': '709-785, courtesy Qingchen, style Yan Lu Gong. An-Shi Rebellion defended Pingyuan/Nephew Manuscript/righteous martyrdom. Yan Qinli Stele/Duobao Pagoda Stele/Nephew Manuscript three masterpieces. "Yan sinew Liu bone" became regular script highest praise. Influenced Liu Gongquan/Zhao Mengfu/Wen Zhengming/Dong Qichang/Wang Duo/Fu Shan/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi entire map.'
    },
    {
        'code': 'H-OYX-294',
        'name_zh': '欧阳询：欧体/楷书四家/初唐四家/九成宫/化度寺/楷书教科书',
        'name_en': 'Ouyang Xun: Ou Style/Regular Four Masters/Early Tang Four Masters/Jiu Cheng Gong/Hua Du Temple/Regular Script Textbook',
        'desc_zh': '初唐书法家，"欧体"楷书方正/严谨/笔画瘦硬(九成宫醴泉铭/化度寺碑/梦奠帖)，"初唐四家"(欧阳询/虞世南/褚遂良/薛稷)之首，唐太宗"得王羲之笔意者惟欧阳询"，成中国楷书/教科书/规范/传承四维典范。',
        'desc_en': 'Early Tang calligrapher, "Ou Style" regular script square/rigorous/strokes thin-hard (Jiu Cheng Gong Liquan Ming/Hua Du Temple Stele/Meng Dian Tie), first of "Early Tang Four Masters" (Ouyang Xun/Yu Shinan/Chu Suiliang/Xue Ji), Tang Taizong "only Ouyang Xun got Wang Xizhi brush intent", becoming Chinese regular script/textbook/standard/transmission four-dimensional paradigm.',
        'modes': [23, 26, 28, 25, 18],
        'reason_zh': '欧阳询以"欧体"楷书方正/严谨/笔画瘦硬成楷书规范/教科书/初学者必临，"初唐四家"之首/唐太宗钦定"得王羲之笔意者惟欧阳询"，成中国楷书/规范/教科书/传承四维奠基。',
        'reason_en': 'Ouyang Xun with "Ou Style" regular script square/rigorous/strokes thin-hard became regular script standard/textbook/beginner must-copy, first of "Early Tang Four Masters"/Tang Taizong designated "only Ouyang Xun got Wang Xizhi brush intent", becoming Chinese regular script/standard/textbook/transmission four-dimensional foundation.',
        'steps_zh': ['欧体楷书：九成宫醴泉铭/化度寺碑/皇甫诞碑/梦奠帖，方正/严谨/笔画瘦硬/结体紧凑/笔意深厚，成楷书规范/教科书/初学者必临第一碑', '初唐四家：欧阳询/虞世南/褚遂良/薛稷"初唐四家"并称，欧为首/方正严谨/虞圆润/褚秀润/薛险绝，确立初唐楷书格局', '王羲之笔意：唐太宗"得王羲之笔意者惟欧阳询/虞世南/褚遂良/薛稷"，欧居首/笔意最深/规范最高', '楷书教科书：九成宫醴泉铭成历代楷书初学者第一碑/欧体字帖成书法教育标准教材/印刷字体(宋体/黑体/楷体)源流', '传承版图：影响虞世南/褚遂良/薛稷/颜真卿/柳公权/苏轼/黄庭坚/米芾/赵孟頫/文徵明/董其昌/王铎/傅山/康有为/启功/沈鹏/欧阳中石全版图'],
        'steps_en': ['Ou Style Regular: Jiu Cheng Gong Liquan Ming/Hua Du Temple Stele/Huangfu Dan Stele/Meng Dian Tie, square/rigorous/strokes thin-hard/structure compact/brush intent deep, became regular standard/textbook/beginner first stele', 'Early Tang Four Masters: Ouyang Xun/Yu Shinan/Chu Suiliang/Xue Ji "Early Tang Four Masters" paired fame, Ou first/square rigorous/Yu round/Chu graceful/Xue perilous, establishing early Tang regular landscape', 'Wang Xizhi Brush Intent: Tang Taizond "only Ouyang Xun/Yu Shinan/Chu Suiliang/Xue Ji got Wang Xizhi brush intent", Ou first/intent deepest/standard highest', 'Regular Textbook: Jiu Cheng Gong Liquan Ming became历代 regular beginner first stele/Ou Style copybooks became calligraphy education standard material/printed fonts (Song/Hei/Kai) origin', 'Transmission Map: Influenced Yu Shinan/Chu Suiliang/Xue Ji/Yan Zhenqing/Liu Gongquan/Su Shi/Huang Tingjian/Mi Fu/Zhao Mengfu/Wen Zhengming/Dong Qichang/Wang Duo/Fu Shan/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi entire map'],
        'expected_zh': '成中国楷书/规范/教科书/传承四维奠基，欧体/九成宫/初唐四家/王羲之笔意/教科书五大遗产',
        'expected_en': 'Become Chinese regular script/standard/textbook/transmission four-dimensional foundation, Ou Style/Jiu Cheng Gong/Early Tang Four Masters/Wang Xizhi brush intent/textbook five great legacies',
        'case_zh': '557-641年，字信本，号松涛。九成宫醴泉铭/化度寺碑/皇甫诞碑/梦奠帖。唐太宗"得王羲之笔意者惟欧阳询"。初唐四家之首。影响虞世南/褚遂良/薛稷/颜真卿/柳公权/苏轼/黄庭坚/米芾/赵孟頫/文徵明/董其昌/王铎/傅山/康有为/启功/沈鹏/欧阳中石全版图。',
        'case_en': '557-641, courtesy Xinben, style Songtao. Jiu Cheng Gong Liquan Ming/Hua Du Temple Stele/Huangfu Dan Stele/Meng Dian Tie. Tang Taizond "only Ouyang Xun got Wang Xizhi brush intent". First of Early Tang Four Masters. Influenced Yu Shinan/Chu Suiliang/Xue Ji/Yan Zhenqing/Liu Gongquan/Su Shi/Huang Tingjian/Mi Fu/Zhao Mengfu/Wen Zhengming/Dong Qichang/Wang Duo/Fu Shan/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi entire map.'
    },
    {
        'code': 'H-LGQ-295',
        'name_zh': '柳公权：柳体/颜筋柳骨/楷书正统/书法风骨/唐末/楷书传承',
        'name_en': 'Liu Gongquan: Liu Style/Yan Sinew Liu Bone/Regular Orthodoxy/Calligraphy Integrity/Late Tang/Regular Transmission',
        'desc_zh': '唐末书法家，"柳体"楷书瘦硬/方正/骨力内含(神策军碑/玄秘塔碑/韦诞帖)，"颜筋柳骨"与颜真卿并称楷书双峰，"用笔贵在笔锋"成楷书笔法金科玉律，成中国楷书/风骨/笔法/传承/风骨五维典范。',
        'desc_en': 'Late Tang calligrapher, "Liu Style" regular script thin-hard/square/bone force contained (Shence Army Stele/Xuanmi Pagoda Stele/Wei Yan Tie), "Yan Sinew Liu Bone" paired with Yan Zhenqing as regular twin peaks, "brush tip precious" became regular script brush law golden rule, becoming Chinese regular script/integrity/brush method/transmission/integrity five-dimensional paradigm.',
        'modes': [23, 26, 28, 25, 18],
        'reason_zh': '柳公权以"柳体"楷书瘦硬/骨力内含成"颜筋柳骨"楷书双峰，"用笔贵在笔锋"成楷书笔法金科玉律，唐末风骨峻峭成楷书风骨传承典范，成中国楷书/风骨/笔法/传承/风骨五维集大成。',
        'reason_en': 'Liu Gongquan with "Liu Style" regular script thin-hard/bone force contained became "Yan Sinew Liu Bone" regular twin peaks, "brush tip precious" became regular brush law golden rule, late Tang integrity lofty became regular integrity transmission paradigm, becoming Chinese regular script/integrity/brush method/transmission/integrity five-dimensional synthesis.',
        'steps_zh': ['柳体楷书：神策军碑/玄秘塔碑/韦诞帖/李玄靖碑，瘦硬/骨力内含/结体疏朗/笔锋外露，成"颜筋柳骨"楷书双峰', '颜筋柳骨：颜真卿雄浑/柳公权瘦硬，"颜筋柳骨"成中国楷书最高评价/双峰并峙/后世楷书评价金标准', '用笔贵锋："用笔贵在笔锋"成楷书笔法金科玉律/教学核心/临摹核心原则，影响后世所有楷书家', '唐末风骨：唐末藩镇割据/宦官专权/柳公权不媚权贵/风骨峻峭/书法/为官/为人三风骨一致', '传承版图：影响赵孟頫/文徵明/董其昌/王铎/傅山/康有为/启功/沈鹏/欧阳中石/欧阳询/虞世南/褚遂良/薛稷/颜真卿/柳公权全版图'],
        'steps_en': ['Liu Style Regular: Shence Army Stele/Xuanmi Pagoda Stele/Wei Yan Tie/Li Xuanjing Stele, thin-hard/bone force contained/structure sparse/brush tip exposed, became "Yan Sinew Liu Bone" regular twin peaks', 'Yan Sinew Liu Bone: Yan Zhenqing masculine/Liu Gongquan thin-hard, "Yan Sinew Liu Bone" became Chinese regular highest evaluation/twin peaks/later regular evaluation gold standard', 'Brush Tip Precious: "Brush usage precious in brush tip" became regular brush law golden rule/teaching core/copying core principle, influenced all later regular calligraphers', 'Late Tang Integrity: Late Tang warlord separatism/eunuch power/Liu Gongquan not flattering power/integrity lofty/calligraphy/official/person three integrities consistent', 'Transmission Map: Influenced Zhao Mengfu/Wen Zhengming/Dong Qichang/Wang Duo/Fu Shan/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi/Ouyang Xun/Yu Shinan/Chu Suiliang/Xue Ji/Yan Zhenqing/Liu Gongquan entire map'],
        'expected_zh': '成中国楷书/风骨/笔法/传承/风骨五维集大成，柳体/颜筋柳骨/用笔贵锋/唐末风骨/传承五大遗产',
        'expected_en': 'Become Chinese regular script/integrity/brush method/transmission/integrity five-dimensional synthesis, Liu Style/Yan Sinew Liu Bone/brush tip precious/late Tang integrity/transmission five great legacies',
        'case_zh': '778-865年，字诚悬。神策军碑/玄秘塔碑/李玄靖碑/韦诞帖。"颜筋柳骨"成楷书最高评价。"用笔贵在笔锋"成金科玉律。影响赵孟頫/文徵明/董其昌/王铎/傅山/康有为/启功/沈鹏/欧阳中石/欧阳询/虞世南/褚遂良/薛稷/颜真卿/柳公权全版图。',
        'case_en': '778-865, courtesy Chengxuan. Shence Army Stele/Xuanmi Pagoda Stele/Li Xuanjing Stele/Wei Yan Tie. "Yan Sinew Liu Bone" became regular highest evaluation. "Brush usage precious in brush tip" became golden rule. Influenced Zhao Mengfu/Wen Zhengming/Dong Qichang/Wang Duo/Fu Shan/Kang Youwei/Qi Gong/Shen Peng/Ouyang Zhongshi/Ouyang Xun/Yu Shinan/Chu Suiliang/Xue Ji/Yan Zhenqing/Liu Gongquan entire map.'
    },
    {
        'code': 'H-GHQ-296',
        'name_zh': '关汉卿：元杂剧/窦娥冤/四大悲剧/元曲大家/戏曲奠基/悲剧美学',
        'name_en': 'Guan Hanqing: Yuan Zaju/Dou E Yuan/Four Great Tragedies/Yuan Drama Master/Drama Foundation/Tragic Aesthetics',
        'desc_zh': '元代戏曲家，"元杂剧"大成，著《窦娥冤》《救风尘》《拜月亭》《单刀会》等十余种，"四大悲剧"之首(窦娥冤/汉宫秋/雷雨/离魂记)，成中国戏曲/悲剧/现实主义/杂剧/传承五维典范。',
        'desc_en': 'Yuan dramatist, "Yuan Zaju" master, authored "Dou E Yuan/Jiu Feng Chen/Bai Yue Ting/Dan Dao Hui" ten-plus works, first of "Four Great Tragedies" (Dou E Yuan/Han Qiu Autumn/Lei Yu/Disunited Soul), becoming Chinese drama/tragedy/realism/zaju/transmission five-dimensional paradigm.',
        'modes': [23, 24, 25, 26, 18],
        'reason_zh': '关汉卿以《窦娥冤》"雪在六月/三尺冤魂"成中国悲剧美学巅峰，十余种杂剧现实主义/关注底层/揭露黑暗，成中国戏曲/悲剧/现实主义/杂剧/传承五维奠基。',
        'reason_en': 'Guan Hanqing reached Chinese tragic aesthetics peak with "Dou E Yuan" "snow in June/three feet wronged soul", ten-plus zaju realism/focus on underclass/expose darkness, becoming Chinese drama/tragedy/realism/zaju/transmission five-dimensional foundation.',
        'steps_zh': ['窦娥冤：雪在六月/三尺冤魂/血溅白练/老母含冤，中国悲剧美学巅峰/冤屈/申冤/伸冤三重奏/感天动地', '杂剧大成：十余种杂剧(救风尘/拜月亭/单刀会/包待制/李逵负荆/望江亭/马陵道/朱履板/调风月/憨汉子/绣鞋记)，现实主义/关注底层/揭露黑暗', '四大悲剧：窦娥冤/马致远汉宫秋/白朴墙头马上/郑光祖倩女离魂，"四大悲剧"之首/悲剧美学奠基', '现实主义：关注卖唱女/倡優/下层百姓命运，揭露封建黑暗/官僚腐败/法律不公，成元杂剧现实主义奠基', '传承版图：影响白朴/马致远/郑光祖/汤显祖/李渔/曹禺/老舍/茅盾/巴金/高行健/莫言戏曲/话剧/小说/现实主义全版图'],
        'steps_en': ['Dou E Yuan: Snow in June/three feet wronged soul/blood splashed white silk/old mother bearing grievance, Chinese tragic aesthetics peak/grievance/appeal/red