#!/usr/bin/env python3
"""
Phase 13-16 完整修复脚本
- 生成 95 位人物完整 v6 Schema JSON
- 添加 M262-M356 共 95 个新模式到 modes_data.json
- 合并到主数据文件 (scenarios_zh/en.json, code_maps.json, scenario_tags.json)
- 运行测试验证
"""

import json
import os
from pathlib import Path

TOOLS_DIR = Path("/opt/data/workspace/Protreptic/tools")
JSON_DIR = TOOLS_DIR / "json"
JSON_DIR.mkdir(exist_ok=True)

# ============================================================
# 1. 定义 95 个新模式 M262-M356 (从 albo artifacts 提取)
# ============================================================

NEW_MODES = {
    # Phase 13: 高加索/中亚/伊斯兰/诗歌/游牧 M262-M281
    "262": {"zh": ["黄金时代统一十字军", "黄金时代+统一+十字军+格鲁吉亚", "黄金时代->统一->十字军->格鲁吉亚", "巴格拉季昂、格鲁吉亚、统一、十字军、黄金时代"], "en": ["Golden Age Unification Crusades", "Golden Age + unification + crusades + Georgia", "Golden Age -> unification -> crusades -> Georgia", "Bagrationi, Georgia, unification, crusades, golden age"]},
    "263": {"zh": ["斯大林苏联化与本土化", "斯大林+苏联化+本土化+格鲁吉亚", "斯大林->苏联化->本土化->格鲁吉亚", "斯大林、格鲁吉亚、苏联化、本土化、铁幕"], "en": ["Stalin Sovietization & Indigenization", "Stalin + sovietization + indigenization + Georgia", "Stalin -> sovietization -> indigenization -> Georgia", "Stalin, Georgia, sovietization, indigenization, iron curtain"]},
    "264": {"zh": ["亚美尼亚帝国罗马帕提亚", "亚美尼亚+帝国+罗马+帕提亚", "亚美尼亚->帝国->罗马->帕提亚", "提格兰大帝、亚美尼亚、罗马、帕提亚、帝国"], "en": ["Armenian Empire Rome Parthia", "Armenia + empire + Rome + Parthia", "Armenia -> empire -> Rome -> Parthia", "Tigranes the Great, Armenia, Rome, Parthia, empire"]},
    "265": {"zh": ["种族灭绝幸存与流散", "种族灭绝+幸存+流散+记忆", "种族灭绝->幸存->流散->记忆", "亚美尼亚、种族灭绝、幸存、流散、记录者"], "en": ["Genocide Survival & Diaspora", "Genocide + survival + diaspora + memory", "Genocide -> survival -> diaspora -> memory", "Armenia, genocide, survival, diaspora, chronicler"]},
    "266": {"zh": ["石油转型世俗伊斯兰", "石油+转型+世俗+伊斯兰", "石油->转型->世俗->伊斯兰", "阿利耶夫、阿塞拜疆、石油、转型、世俗、伊斯兰"], "en": ["Oil Transition Secular Islam", "Oil + transition + secular + Islam", "Oil -> transition -> secular -> Islam", "Aliyev, Azerbaijan, oil, transition, secular, Islam"]},
    "267": {"zh": ["东方诗人智慧爱情哲学", "诗人+智慧+爱情+哲学", "诗人->智慧->爱情->哲学", "尼扎米、阿塞拜疆、诗人、智慧、爱情、哲学"], "en": ["Oriental Poet Wisdom Love Philosophy", "Poet + wisdom + love + philosophy", "Poet -> wisdom -> love -> philosophy", "Nizami, Azerbaijan, poet, wisdom, love, philosophy"]},
    "268": {"zh": ["抵抗奥斯曼瓦拉几亚独立", "抵抗+奥斯曼+瓦拉几亚+独立", "抵抗->奥斯曼->瓦拉几亚->独立", "斯特凡、摩尔多瓦、奥斯曼、抵抗、独立"], "en": ["Resistance Ottoman Wallachia Independence", "Resistance + Ottoman + Wallachia + independence", "Resistance -> Ottoman -> Wallachia -> independence", "Stephen, Moldova, Ottoman, resistance, independence"]},
    "269": {"zh": ["知识分子异见极权真理", "知识分子+异见+极权+真理", "知识分子->异见->极权->真理", "布鲁塞、罗马尼亚、知识分子、异见、极权、真理"], "en": ["Intellectual Dissent Totalitarianism Truth", "Intellectual + dissent + totalitarianism + truth", "Intellectual -> dissent -> totalitarianism -> truth", "Braes, Romania, intellectual, dissent, totalitarianism, truth"]},
    "270": {"zh": ["法西斯神秘正教青年", "法西斯+神秘+正教+青年", "法西斯->神秘->正教->青年", "科德雷亚努、罗马尼亚、铁卫团、法西斯、神秘、正教、青年"], "en": ["Fascism Mysticism Orthodoxy Youth", "Fascism + mysticism + orthodoxy + youth", "Fascism -> mysticism -> orthodoxy -> youth", "Codreanu, Romania, Iron Guard, fascism, mysticism, orthodoxy, youth"]},
    "271": {"zh": ["独裁体操革命处决", "独裁+体操+革命+处决", "独裁->体操->革命->处决", "切奥塞斯库、罗马尼亚、独裁、体操、革命、处决"], "en": ["Dictatorship Gymnastics Revolution Execution", "Dictatorship + gymnastics + revolution + execution", "Dictatorship -> gymnastics -> revolution + execution", "Ceausescu, Romania, dictatorship, gymnastics, revolution, execution"]},
    "272": {"zh": ["核放弃首都迁移多楔外交", "核放弃+首都迁移+多楔外交+哈萨克", "核放弃->首都迁移->多楔外交->哈萨克", "纳扎尔巴耶夫、哈萨克斯坦、核放弃、阿斯塔纳、多楔外交"], "en": ["Nuclear Abandonment Capital Move Multi-Wedge Diplomacy", "Nuclear abandonment + capital move + multi-wedge diplomacy + Kazakhstan", "Nuclear abandonment -> capital move -> multi-wedge diplomacy -> Kazakhstan", "Nazarbayev, Kazakhstan, nuclear abandonment, Astana, multi-wedge diplomacy"]},
    "273": {"zh": ["草原哲学家教育启蒙", "哲学家+教育+启蒙+草原", "哲学家->教育->启蒙->草原", "阿拜、哈萨克、诗人、哲学家、教育、启蒙"], "en": ["Steppe Philosopher Education Enlightenment", "Philosopher + education + enlightenment + steppe", "Philosopher -> education -> enlightenment -> steppe", "Abai, Kazakh, poet, philosopher, education, enlightenment"]},
    "274": {"zh": ["铁腕棉花水世俗", "铁腕+棉花+水+世俗", "铁腕->棉花->水->世俗", "卡里莫夫、乌兹别克斯坦、铁腕、棉花、水、世俗"], "en": ["Iron Fist Cotton Water Secularism", "Iron fist + cotton + water + secularism", "Iron fist -> cotton -> water -> secularism", "Karimov, Uzbekistan, iron fist, cotton, water, secularism"]},
    "275": {"zh": ["帖木儿帝国征服文化融合", "征服+帝国+文化+融合", "征服->帝国->文化->融合", "帖木儿、中亚、征服、帝国、撒马尔罕、文化融合"], "en": ["Timurid Empire Conquest Cultural Fusion", "Conquest + empire + culture + fusion", "Conquest -> empire -> culture -> fusion", "Timur, Central Asia, conquest, empire, Samarkand, cultural fusion"]},
    "276": {"zh": ["图兰主义游牧苏联独立", "图兰主义+游牧+苏联+独立", "图兰主义->游牧->苏联->独立", "阿特姆别科夫、吉尔吉斯、图兰主义、游牧、苏联、独立"], "en": ["Turanism Nomadism Soviet Independence", "Turanism + nomadism + Soviet + independence", "Turanism -> nomadism -> Soviet -> independence", "Atambayev, Kyrgyz, Turanism, nomadism, Soviet, independence"]},
    "277": {"zh": ["玛纳斯史诗口述英雄统一", "史诗+口述+英雄+统一", "史诗->口述->英雄->统一", "玛纳斯、吉尔吉斯、史诗、英雄、统一、口述传统"], "en": ["Manas Epic Oral Hero Unification", "Epic + oral + hero + unification", "Epic -> oral -> hero -> unification", "Manas, Kyrgyz, epic, hero, unification, oral tradition"]},
    "278": {"zh": ["内战波斯认同水移民", "内战+波斯认同+水+移民", "内战->波斯认同->水+移民", "拉赫蒙、塔吉克、内战、波斯认同、水、移民"], "en": ["Civil War Persian Identity Water Migration", "Civil war + Persian identity + water + migration", "Civil war -> Persian identity -> water -> migration", "Rahmon, Tajikistan, civil war, Persian identity, water, migration"]},
    "279": {"zh": ["波斯诗歌鲁达基宫廷语言", "诗歌+鲁达基+宫廷+语言", "诗歌->鲁达基->宫廷->语言", "鲁达基、塔吉克、波斯诗歌、宫廷、语言"], "en": ["Persian Poetry Rudaki Court Language", "Poetry + Rudaki + court + language", "Poetry -> Rudaki -> court -> language", "Rudaki, Tajik, Persian poetry, court, language"]},
    "280": {"zh": ["永久中性阿哈尔捷金天然气", "永久中性+阿哈尔捷金+天然气+土库曼", "永久中性->阿哈尔捷金->天然气->土库曼", "别尔德穆哈梅多夫、土库曼、中性、马、天然气"], "en": ["Permanent Neutrality Akhal-Teke Natural Gas", "Permanent neutrality + Akhal-Teke + natural gas + Turkmenistan", "Permanent neutrality -> Akhal-Teke -> natural gas -> Turkmenistan", "Berdimuhamedov, Turkmenistan, neutrality, horses, natural gas"]},
    "281": {"zh": ["土库曼诗歌精神抵抗统一", "诗歌+精神+抵抗+统一", "诗歌->精神->抵抗->统一", "马格特姆古里、土库曼、诗人、精神、抵抗、统一"], "en": ["Turkmen Poetry Spirit Resistance Unification", "Poetry + spirit + resistance + unification", "Poetry -> spirit -> resistance -> unification", "Magtymguly, Turkmen, poetry, spirit, resistance, unification"]},

    # Phase 14: 东南亚/大洋洲/游击/发展主义/王室 M282-M306
    "282": {"zh": ["游击独立与竹子外交", "游击+独立+统一+竹子外交", "游击->独立->统一->竹子外交", "胡志明、越南、游击、独立、竹子外交"], "en": ["Guerrilla Independence & Bamboo Diplomacy", "Guerrilla + independence + unification + bamboo diplomacy", "Guerrilla -> independence -> unification -> bamboo diplomacy", "Ho Chi Minh, Vietnam, guerrilla, independence, bamboo diplomacy"]},
    "283": {"zh": ["抗蒙军事与游击水战", "抗元+游击+水战+兵法", "抗元->游击->水战->兵法", "陈兴道、越南、抗元、水战、兵法"], "en": ["Anti-Mongol Military & Guerrilla Naval Genius", "Anti-Yuan + guerrilla + naval warfare + tactics", "Anti-Yuan -> guerrilla -> naval warfare -> tactics", "Tran Hung Dao, Vietnam, anti-Yuan, naval warfare, tactics"]},
    "284": {"zh": ["红王子中立与三王子联合", "红王子+中立+三王子+联合", "红王子->中立->三王子->联合", "苏发努冯、老挝、红王子、中立、联合"], "en": ["Red Prince Neutrality & Three Princes Unity", "Red Prince + neutrality + three princes + unity", "Red Prince -> neutrality -> three princes -> unity", "Souphanouvong, Laos, Red Prince, neutrality, unity"]},
    "285": {"zh": ["澜沧王国佛教与万象统一", "澜沧+万象+佛教+统一", "澜沧->万象->佛教->统一", "法昂、老挝、澜沧、佛教、万象"], "en": ["Lan Xang Kingdom Buddhism & Vientiane Unity", "Lan Xang + Vientiane + Buddhism + unity", "Lan Xang -> Vientiane -> Buddhism -> unity", "Fa Ngum, Laos, Lan Xang, Buddhism, Vientiane"]},
    "286": {"zh": ["国王舞者外交与中立生存", "国王+舞者+外交+中立", "国王->舞者->外交->中立", "西哈努克、柬埔寨、国王、舞者、外交、中立"], "en": ["King Dancer Diplomacy & Neutral Survival", "King + dancer + diplomacy + neutrality", "King -> dancer -> diplomacy -> neutrality", "Sihanouk, Cambodia, king, dancer, diplomacy, neutrality"]},
    "287": {"zh": ["农业乌托邦与阶级清洗自毁", "农业+乌托邦+清洗+自毁", "农业->乌托邦->清洗->自毁", "波尔布特、柬埔寨、农业、乌托邦、清洗、自毁"], "en": ["Agrarian Utopia & Class Purge Self-Destruction", "Agrarian + utopia + purge + self-destruction", "Agrarian -> utopia -> purge -> self-destruction", "Pol Pot, Cambodia, agrarian, utopia, purge, self-destruction"]},
    "288": {"zh": ["吴哥佛教与医院水利基建", "佛教+医院+水利+基建", "佛教->医院->水利->基建", "阇耶跋摩、吴哥、佛教、医院、水利、基建"], "en": ["Angkor Buddhism & Hospital Water Infrastructure", "Buddhism + hospitals + water + infrastructure", "Buddhism -> hospitals -> water -> infrastructure", "Jayavarman VII, Angkor, Buddhism, hospitals, water, infrastructure"]},
    "289": {"zh": ["抵抗泰越与夹缝生存", "抵抗+泰国+越南+夹缝", "抵抗->泰国->越南->夹缝", "杜翁、柬埔寨、抵抗、泰国、越南、夹缝"], "en": ["Resistance Thai-Vietnam & Squeeze Survival", "Resistance + Thailand + Vietnam + squeeze", "Resistance -> Thailand -> Vietnam -> squeeze", "Duong, Cambodia, resistance, Thailand, Vietnam, squeeze"]},
    "290": {"zh": ["改革现代化免殖民绝对君主", "改革+现代化+免殖民+绝对君主", "改革->现代化->免殖民->绝对君主", "朱拉隆功、泰国、改革、现代化、免殖民、绝对君主"], "en": ["Reform Modernization Anti-Colonial Absolute Monarchy", "Reform + modernization + anti-colonial + absolute monarchy", "Reform -> modernization -> anti-colonial -> absolute monarchy", "Chulalongkorn, Thailand, reform, modernization, anti-colonial, absolute monarchy"]},
    "291": {"zh": ["学生起义民主军事循环", "学生起义+民主+军事+循环", "学生起义->民主->军事->循环", "披耶、泰国、学生起义、民主、军事、循环"], "en": ["Student Uprising Democracy Military Cycle", "Student uprising + democracy + military + cycle", "Student uprising -> democracy -> military -> cycle", "Phibun, Thailand, student uprising, democracy, military, cycle"]},
    "292": {"zh": ["发展主义多元眼镜长寿", "发展主义+多元+眼镜+长寿", "发展主义->多元->眼镜->长寿", "马哈蒂尔、马来西亚、发展主义、多元、眼镜、长寿"], "en": ["Developmentalism Diversity Glasses Longevity", "Developmentalism + diversity + glasses + longevity", "Developmentalism -> diversity -> glasses + longevity", "Mahathir, Malaysia, developmentalism, diversity, glasses, longevity"]},
    "293": {"zh": ["温和独立联邦种族平衡", "温和独立+联邦+种族+平衡", "温和独立->联邦->种族->平衡", "东姑、马来亚、独立、联邦、种族、平衡"], "en": ["Moderate Independence Federal Racial Balance", "Moderate independence + federal + racial + balance", "Moderate independence -> federal -> racial -> balance", "Tunku, Malaya, independence, federal, racial, balance"]},
    "294": {"zh": ["独立将军女儿民主军事", "独立将军+女儿+民主+军事", "独立将军->女儿->民主->军事", "昂山、缅甸、独立、将军、女儿、民主、军事"], "en": ["Independence General Daughter Democracy Military", "Independence general + daughter + democracy + military", "Independence general -> daughter -> democracy -> military", "Aung San, Myanmar, independence, general, daughter, democracy, military"]},
    "295": {"zh": ["佛教社会主义民主政变僧侣", "佛教社会主义+民主+政变+僧侣", "佛教社会主义->民主->政变->僧侣", "吴努、缅甸、佛教社会主义、民主、政变、僧侣"], "en": ["Buddhist Socialism Democracy Coup Monks", "Buddhist socialism + democracy + coup + monks", "Buddhist socialism -> democracy -> coup -> monks", "U Nu, Myanmar, Buddhist socialism, democracy, coup, monks"]},
    "296": {"zh": ["军事隔离佛教迷信经济自毁", "军事隔离+佛教迷信+经济+自毁", "军事隔离->佛教迷信->经济->自毁", "内温、缅甸、军事隔离、佛教迷信、经济、自毁"], "en": ["Military Isolation Buddhist Superstition Economy Self-Destruction", "Military isolation + Buddhist superstition + economy + self-destruction", "Military isolation -> Buddhist superstition -> economy -> self-destruction", "Ne Win, Myanmar, military isolation, Buddhist superstition, economy, self-destruction"]},
    "297": {"zh": ["种族清洗无国籍海上幸存", "种族清洗+无国籍+海上+幸存", "种族清洗->无国籍->海上->幸存", "罗兴亚、缅甸、种族清洗、无国籍、海上、幸存"], "en": ["Ethnic Cleansing Stateless Sea Survival", "Ethnic cleansing + stateless + sea + survival", "Ethnic cleansing -> stateless -> sea -> survival", "Rohingya, Myanmar, ethnic cleansing, stateless, sea, survival"]},
    "298": {"zh": ["奴隶废除铁路行政现代化", "奴隶废除+铁路+行政+现代化", "奴隶废除->铁路->行政->现代化", "拉玛五世、朱拉隆功、奴隶废除、铁路、行政、现代化"], "en": ["Slavery Abolition Railway Administration Modernization", "Slavery abolition + railway + administration + modernization", "Slavery abolition -> railway -> administration -> modernization", "Rama V, Chulalongkorn, slavery abolition, railway, administration, modernization"]},
    "299": {"zh": ["泛亚非不结盟与万隆指导", "泛亚非+不结盟+万隆+指导", "泛亚非->不结盟->万隆->指导", "苏加诺、印尼、泛亚非、不结盟、万隆、指导"], "en": ["Pan-Asian-African Non-Aligned Bandung Leadership", "Asian-African + Non-Aligned + Bandung + Leadership", "Asian-African -> Non-Aligned -> Bandung -> Leadership", "Sukarno, Indonesia, Asian-African, Non-Aligned, Bandung, Leadership"]},
    "300": {"zh": ["新秩序经济奇迹与腐败华人", "新秩序+经济奇迹+腐败+华人", "新秩序->经济奇迹->腐败->华人", "苏哈托、印尼、新秩序、经济奇迹、腐败、华人"], "en": ["New Order Economic Miracle & Corruption Chinese", "New Order + economic miracle + corruption + Chinese", "New Order -> economic miracle -> corruption -> Chinese", "Suharto, Indonesia, New Order, economic miracle, corruption, Chinese"]},
    "301": {"zh": ["医生小说家革命殉道教育", "医生+小说+革命+殉道", "医生->小说->革命->殉道", "里萨尔、菲律宾、医生、小说、革命、殉道、教育"], "en": ["Doctor Novelist Revolutionary Martyrdom Education", "Doctor + novel + revolution + martyrdom", "Doctor -> novel -> revolution -> martyrdom", "Rizal, Philippines, doctor, novel, revolution, martyrdom, education"]},
    "302": {"zh": ["黄衣人民权力与民主殉道妻子", "黄衣+人民+权力+民主", "黄衣->人民->权力+民主", "阿基诺、菲律宾、黄衣、人民、权力、民主、殉道、妻子"], "en": ["Yellow People Power & Democratic Martyr Widow", "Yellow + people + power + democracy", "Yellow -> people -> power -> democracy", "Aquino, Philippines, yellow, people, power, democracy, martyr, widow"]},
    "303": {"zh": ["从第三世界到第一与法治精英", "第三世界+第一+法治+精英", "第三世界->第一->法治->精英", "李光耀、新加坡、第三世界、第一、法治、精英"], "en": ["From Third World to First & Rule of Law Elite", "Third World + First + Rule of Law + Elite", "Third World -> First -> Rule of Law -> Elite", "Lee Kuan Yew, Singapore, Third World, First, Rule of Law, Elite"]},
    "304": {"zh": ["接班开放自由与精英转型", "接班+开放+自由+转型", "接班->开放->自由->转型", "吴作栋、新加坡、接班、开放、自由、转型、精英"], "en": ["Succession Opening Freedom & Elite Transformation", "Succession + opening + freedom + transformation", "Succession -> opening -> freedom -> transformation", "Goh Chok Tong, Singapore, succession, opening, freedom, transformation, elite"]},
    "305": {"zh": ["苏丹石油沙里亚与福利绝对", "苏丹+石油+沙里亚+福利", "苏丹->石油->沙里亚->福利", "博尔基亚、文莱、苏丹、石油、沙里亚、福利、绝对"], "en": ["Sultan Oil Sharia & Welfare Absolute", "Sultan + oil + Sharia + welfare", "Sultan -> oil -> Sharia -> welfare", "Bolkiah, Brunei, Sultan, oil, Sharia, welfare, absolute"]},
    "306": {"zh": ["游击总统诺贝尔与石油和解", "游击+总统+诺贝尔+和解", "游击->总统->诺贝尔->和解", "古斯芒、东帝汶、游击、总统、诺贝尔、和解、石油"], "en": ["Guerrilla President Nobel & Oil Reconciliation", "Guerrilla + president + Nobel + reconciliation", "Guerrilla -> president -> Nobel -> reconciliation", "Gusmao, East Timor, guerrilla, president, Nobel, reconciliation, oil"]},

    # Phase 15: 南亚/中东/非洲/后冲突 M307-M336
    "307": {"zh": ["毛派和平共和国联邦过渡", "毛派+和平+共和国+联邦+过渡", "毛派->和平->共和国->联邦->过渡", "普拉昌达、尼泊尔、毛派、和平、共和国、联邦、过渡"], "en": ["Maoist Peace Republic Federal Transition", "Maoist + peace + republic + federal + transition", "Maoist -> peace -> republic -> federal -> transition", "Prachanda, Nepal, Maoist, peace, republic, federal, transition"]},
    "308": {"zh": ["国王屠杀君主废除共和国悲剧", "国王屠杀+君主废除+共和国+悲剧", "国王屠杀->君主废除->共和国->悲剧", "比伦德拉、尼泊尔、国王屠杀、君主废除、共和国、悲剧"], "en": ["Royal Massacre Monarchy Abolition Republic Tragedy", "Royal massacre + monarchy abolition + republic + tragedy", "Royal massacre -> monarchy abolition -> republic -> tragedy", "Birendra, Nepal, royal massacre, monarchy abolition, republic, tragedy"]},
    "309": {"zh": ["龙王民主宪法幸福退位", "龙王+民主+宪法+幸福+退位", "龙王->民主->宪法->幸福->退位", "吉格梅、不丹、龙王、民主、宪法、幸福、退位"], "en": ["Dragon King Democracy Constitution Happiness Abdication", "Dragon king + democracy + constitution + happiness + abdication", "Dragon king -> democracy -> constitution -> happiness -> abdication", "Jigme, Bhutan, dragon king, democracy, constitution, happiness, abdication"]},
    "310": {"zh": ["扎布德隆统一宗堡佛教法王", "统一+宗堡+佛教+法王", "统一->宗堡->佛教->法王", "扎布德隆、不丹、统一、堡垒、佛教、法王"], "en": ["Zhabdrung Unification Dzong Buddhism Dharma King", "Unification + dzong + Buddhism + dharma king", "Unification -> dzong -> Buddhism -> dharma king", "Zhabdrung, Bhutan, unification, dzong, Buddhism, dharma king"]},
    "311": {"zh": ["统一佛教水利石碑阿努拉德普拉", "统一+佛教+水利+石碑+阿努拉德普拉", "统一->佛教->水利->石碑->阿努拉德普拉", "杜特加穆努、斯里兰卡、统一、佛教、水利、石碑"], "en": ["Unification Buddhism Water Stupa Anuradhapura", "Unification + Buddhism + water + stupa + Anuradhapura", "Unification -> Buddhism -> water -> stupa -> Anuradhapura", "Dutugemunu, Sri Lanka, unification, Buddhism, water, stupa"]},
    "312": {"zh": ["僧伽罗佛教社会主义妇女总理", "僧伽罗+佛教+社会主义+妇女+总理", "僧伽罗->佛教->社会主义->妇女->总理", "班达拉奈克、斯里兰卡、僧伽罗、佛教、社会主义、妇女、总理"], "en": ["Sinhala Buddhism Socialism Woman Prime Minister", "Sinhala + Buddhism + socialism + woman + prime minister", "Sinhala -> Buddhism -> socialism -> woman -> prime minister", "Bandaranaike, Sri Lanka, Sinhala, Buddhism, socialism, woman, PM"]},
    "313": {"zh": ["民主气候流亡岛国生存", "民主+气候+流亡+岛国+生存", "民主->气候->流亡->岛国->生存", "纳希德、马尔代夫、民主、气候、流亡、岛国、生存"], "en": ["Democracy Climate Exile Island Survival", "Democracy + climate + exile + island + survival", "Democracy -> climate -> exile -> island -> survival", "Nasheed, Maldives, democracy, climate, exile, island, survival"]},
    "314": {"zh": ["苏丹伊斯兰贸易印度洋珊瑚", "苏丹+伊斯兰+贸易+印度洋+珊瑚", "苏丹->伊斯兰->贸易->印度洋->珊瑚", "毛姆、马尔代夫、苏丹、伊斯兰、贸易、印度洋、珊瑚"], "en": ["Sultan Islam Trade Indian Ocean Coral", "Sultan + Islam + trade + Indian Ocean + coral", "Sultan -> Islam -> trade -> Indian Ocean -> coral", "Maumoon, Maldives, Sultan, Islam, trade, Indian Ocean, coral"]},
    "315": {"zh": ["部落统一阿拉伯春天内战霍乱", "部落统一+阿拉伯春天+内战+霍乱", "部落统一->阿拉伯春天->内战->霍乱", "萨利赫、也门、部落、统一、阿拉伯春天、内战、霍乱"], "en": ["Tribal Unity Arab Spring Civil War Cholera", "Tribal unity + Arab Spring + civil war + cholera", "Tribal unity -> Arab Spring -> civil war -> cholera", "Saleh, Yemen, tribal unity, Arab Spring, civil war, cholera"]},
    "316": {"zh": ["扎伊德什叶抵抗导弹红海", "扎伊德+什叶+抵抗+导弹+红海", "扎伊德->什叶->抵抗->导弹->红海", "胡塞、也门、扎伊德、什叶、抵抗、导弹、红海"], "en": ["Zaydi Shia Resistance Missiles Red Sea", "Zaydi + Shia + resistance + missiles + Red Sea", "Zaydi -> Shia -> resistance -> missiles -> Red Sea", "Houthi, Yemen, Zaydi, Shia, resistance, missiles, Red Sea"]},
    "317": {"zh": ["苏丹现代化中立调解香料", "苏丹+现代化+中立+调解+香料", "苏丹->现代化->中立->调解+香料", "卡布斯、阿曼、苏丹、现代化、中立、调解、香料"], "en": ["Sultan Modernization Neutrality Mediation Spices", "Sultan + modernization + neutrality + mediation + spices", "Sultan -> modernization -> neutrality -> mediation + spices", "Qaboos, Oman, Sultan, modernization, neutrality, mediation, spices"]},
    "318": {"zh": ["伊巴德伊玛目贸易东非赞比亚", "伊巴德+伊玛目+贸易+东非+赞比亚", "伊巴德->伊玛目->贸易->东非->赞比亚", "蒂普、阿曼、伊巴德、伊玛目、贸易、东非、赞比亚"], "en": ["Ibadi Imam Trade East Africa Zambia", "Ibadi + Imam + trade + East Africa + Zambia", "Ibadi -> Imam -> trade -> East Africa -> Zambia", "Tippu Tip, Oman, Ibadi, Imam, trade, East Africa, Zambia"]},
    "319": {"zh": ["石油福利议会伊拉克入侵解放", "石油福利+议会+伊拉克入侵+解放", "石油福利->议会->伊拉克入侵->解放", "贾比尔、科威特、石油福利、议会、伊拉克入侵、解放"], "en": ["Oil Welfare Parliament Iraq Invasion Liberation", "Oil welfare + parliament + Iraq invasion + liberation", "Oil welfare -> parliament -> Iraq invasion -> liberation", "Jaber, Kuwait, oil welfare, parliament, Iraq invasion, liberation"]},
    "320": {"zh": ["改革珍珠什叶逊尼沙特桥梁", "改革+珍珠+什叶逊尼+沙特+桥梁", "改革->珍珠->什叶逊尼->沙特->桥梁", "哈马德、巴林、改革、珍珠、什叶逊尼、沙特、桥梁"], "en": ["Reform Pearls Shia-Sunni Saudi Bridge", "Reform + pearls + Shia-Sunni + Saudi + bridge", "Reform -> pearls -> Shia-Sunni -> Saudi -> bridge", "Hamad, Bahrain, reform, pearls, Shia-Sunni, Saudi, bridge"]},
    "321": {"zh": ["天然气半岛世界杯调解小国", "天然气+半岛+世界杯+调解+小国", "天然气->半岛->世界杯->调解->小国", "塔米姆、卡塔尔、天然气、半岛、世界杯、调解、小国"], "en": ["Natural Gas Peninsula World Cup Mediation Small State", "Natural gas + peninsula + World Cup + mediation + small state", "Natural gas -> peninsula -> World Cup -> mediation -> small state", "Tamim, Qatar, natural gas, peninsula, World Cup, mediation, small state"]},
    "322": {"zh": ["联邦石油宽容女性太空火星", "联邦+石油+宽容+女性+太空+火星", "联邦->石油->宽容->女性->太空->火星", "扎耶德、阿联酋、联邦、石油、宽容、女性、太空、火星"], "en": ["Federation Oil Tolerance Women Space Mars", "Federation + oil + tolerance + women + space + Mars", "Federation -> oil -> tolerance -> women -> space -> Mars", "Zayed, UAE, federation, oil, tolerance, women, space, Mars"]},
    "323": {"zh": ["哈希姆巴勒斯坦和平水难民", "哈希姆+巴勒斯坦+和平+水+难民", "哈希姆->巴勒斯坦->和平->水+难民", "阿卜杜拉、约旦、哈希姆、巴勒斯坦、和平、水、难民"], "en": ["Hashemite Palestine Peace Water Refugees", "Hashemite + Palestine + peace + water + refugees", "Hashemite -> Palestine -> peace + water -> refugees", "Abdullah, Jordan, Hashemite, Palestine, peace, water, refugees"]},
    "324": {"zh": ["宗派权力分享内战诗人雪松", "宗派权力分享+内战+诗人+雪松", "宗派权力分享->内战->诗人->雪松", "蒙杰姆、黎巴嫩、宗派权力分享、内战、诗人、雪松"], "en": ["Sectarian Power Sharing Civil War Poets Cedars", "Sectarian power sharing + civil war + poets + cedars", "Sectarian power sharing -> civil war -> poets -> cedars", "Gemayel, Lebanon, sectarian power sharing, civil war, poets, cedars"]},
    "325": {"zh": ["阿拉维内战化武俄伊朗生存", "阿拉维+内战+化武+俄+伊朗+生存", "阿拉维->内战->化武->俄->伊朗->生存", "阿萨德、叙利亚、阿拉维、内战、化武、俄、伊朗、生存"], "en": ["Alawi Civil War Chemical Weapons Russia Iran Survival", "Alawi + civil war + chemical weapons + Russia + Iran + survival", "Alawi -> civil war -> chemical weapons -> Russia -> Iran -> survival", "Assad, Syria, Alawi, civil war, chemical weapons, Russia, Iran, survival"]},
    "326": {"zh": ["什叶大阿亚图拉政治调解反美伊朗", "什叶大阿亚图拉+政治调解+反美+伊朗", "什叶大阿亚图拉->政治调解->反美->伊朗", "西斯特拉尼、伊拉克、什叶大阿亚图拉、政治调解、反美、伊朗"], "en": ["Shia Grand Ayatollah Political Mediation Anti-US Iran", "Shia Grand Ayatollah + political mediation + anti-US + Iran", "Shia Grand Ayatollah -> political mediation -> anti-US -> Iran", "Sistani, Iraq, Shia Grand Ayatollah, political mediation, anti-US, Iran"]},
    "327": {"zh": ["联邦约鲁巴免费教育区域自治", "联邦+约鲁巴+免费教育+区域自治", "联邦->约鲁巴->免费教育->区域自治", "阿沃洛沃、尼日利亚、联邦、约鲁巴、免费教育、区域自治"], "en": ["Federal Yoruba Free Education Regional Autonomy", "Federal + Yoruba + free education + regional autonomy", "Federal -> Yoruba -> free education -> regional autonomy", "Awolowo, Nigeria, federal, Yoruba, free education, regional autonomy"]},
    "328": {"zh": ["泛非首任总统伊博报纸民族", "泛非+首任总统+伊博+报纸+民族", "泛非->首任总统->伊博->报纸->民族", "阿齐基韦、尼日利亚、泛非、首任总统、伊博、报纸、民族"], "en": ["Pan-African First President Igbo Newspaper Nation", "Pan-African + first president + Igbo + newspaper + nation", "Pan-African -> first president -> Igbo -> newspaper -> nation", "Azikiwe, Nigeria, Pan-African, first president, Igbo, newspaper, nation"]},
    "329": {"zh": ["独立马乌马乌土地部落族长", "独立+马乌马乌+土地+部落+族长", "独立->马乌马乌->土地->部落->族长", "肯雅塔、肯尼亚、独立、马乌马乌、土地、部落、族长"], "en": ["Independence Mau Mau Land Tribe Patriarch", "Independence + Mau Mau + land + tribe + patriarch", "Independence -> Mau Mau -> land -> tribe + patriarch", "Kenyatta, Kenya, independence, Mau Mau, land, tribe, patriarch"]},
    "330": {"zh": ["乌贾马非洲社会主义教师斯瓦希里", "乌贾马+非洲社会主义+教师+斯瓦希里", "乌贾马->非洲社会主义->教师->斯瓦希里", "尼雷尔、坦桑尼亚、乌贾马、非洲社会主义、教师、斯瓦希里"], "en": ["Ujamaa African Socialism Teacher Swahili", "Ujamaa + African socialism + teacher + Swahili", "Ujamaa -> African socialism -> teacher -> Swahili", "Nyerere, Tanzania, Ujamaa, African socialism, teacher, Swahili"]},
    "331": {"zh": ["土地改革独裁恶性通胀钻石遗产", "土地改革+独裁+恶性通胀+钻石+遗产", "土地改革->独裁->恶性通胀->钻石->遗产", "穆加贝、津巴布韦、土地改革、独裁、恶性通胀、钻石、遗产"], "en": ["Land Reform Dictatorship Hyperinflation Diamonds Legacy", "Land reform + dictatorship + hyperinflation + diamonds + legacy", "Land reform -> dictatorship -> hyperinflation -> diamonds + legacy", "Mugabe, Zimbabwe, land reform, dictatorship, hyperinflation, diamonds, legacy"]},
    "332": {"zh": ["真相和解诺贝尔神职彩虹道德", "真相和解+诺贝尔+神职+彩虹+道德", "真相和解->诺贝尔->神职->彩虹->道德", "图图、南非、真相和解、诺贝尔、神职、彩虹、道德"], "en": ["Truth Reconciliation Nobel Clergy Rainbow Morality", "Truth reconciliation + Nobel + clergy + rainbow + morality", "Truth reconciliation -> Nobel -> clergy -> rainbow + morality", "Tutu, South Africa, truth reconciliation, Nobel, clergy, rainbow, morality"]},
    "333": {"zh": ["皇帝现代化非洲联盟拉斯塔神性", "皇帝+现代化+非洲联盟+拉斯塔+神性", "皇帝->现代化->非洲联盟->拉斯塔->神性", "海尔、埃塞俄比亚、皇帝、现代化、非洲联盟、拉斯塔、神性"], "en": ["Emperor Modernization African Union Rastafari Divinity", "Emperor + modernization + African Union + Rastafari + divinity", "Emperor -> modernization -> African Union -> Rastafari + divinity", "Selassie, Ethiopia, emperor, modernization, African Union, Rastafari, divinity"]},
    "334": {"zh": ["泛非非洲统一政变流亡加纳", "泛非+非洲统一+政变+流亡+加纳", "泛非->非洲统一->政变->流亡->加纳", "恩克鲁玛、加纳、泛非、非洲统一、政变、流亡、加纳"], "en": ["Pan-African African Unity Coup Exile Ghana", "Pan-African + African unity + coup + exile + Ghana", "Pan-African -> African unity -> coup -> exile -> Ghana", "Nkrumah, Ghana, Pan-African, African unity, coup, exile, Ghana"]},
    "335": {"zh": ["黑人精神诗人总统法语文化非洲", "黑人精神+诗人总统+法语+文化+非洲", "黑人精神->诗人总统->法语->文化->非洲", "桑戈尔、塞内加尔、黑人精神、诗人总统、法语、文化、非洲"], "en": ["Negritude Poet President French Culture Africa", "Negritude + poet president + French + culture + Africa", "Negritude -> poet president -> French -> culture + Africa", "Senghor, Senegal, Negritude, poet president, French, culture, Africa"]},
    "336": {"zh": ["稳定可可法国和平大教堂奇迹", "稳定+可可+法国+和平+大教堂+奇迹", "稳定->可可->法国->和平->大教堂->奇迹", "乌弗埃、科特迪瓦、稳定、可可、法国、和平、大教堂、奇迹"], "en": ["Stability Cocoa France Peace Cathedral Miracle", "Stability + cocoa + France + peace + cathedral + miracle", "Stability -> cocoa -> France -> peace -> cathedral + miracle", "Houphouet-Boigny, Ivory Coast, stability, cocoa, France, peace, cathedral, miracle"]},

    # Phase 16: 拉美/加勒比/北美/原住民 M337-M356
    "337": {"zh": ["民主安全反游击阿尔瓦罗巴拉圭", "民主安全+反游击+阿尔瓦罗+巴拉圭", "民主安全->反游击->阿尔瓦罗->巴拉圭", "乌里韦、哥伦比亚、民主安全、反游击、阿尔瓦罗、巴拉圭"], "en": ["Democratic Security Anti-Guerrilla Alvaro Paraguay", "Democratic security + anti-guerrilla + Alvaro + Paraguay", "Democratic security -> anti-guerrilla -> Alvaro -> Paraguay", "Uribe, Colombia, democratic security, anti-guerrilla, Alvaro, Paraguay"]},
    "338": {"zh": ["公民革命美元化中国阿桑奇庇护", "公民革命+美元化+中国+阿桑奇+庇护", "公民革命->美元化->中国->阿桑奇->庇护", "科雷亚、厄瓜多尔、公民革命、美元化、中国、阿桑奇、庇护"], "en": ["Citizen Revolution Dollarization China Assange Asylum", "Citizen revolution + dollarization + China + Assange + asylum", "Citizen revolution -> dollarization -> China -> Assange -> asylum", "Correa, Ecuador, citizen revolution, dollarization, China, Assange, asylum"]},
    "339": {"zh": ["可可原住民总统气候海洋权利", "可可+原住民+总统+气候+海洋+权利", "可可->原住民->总统->气候->海洋->权利", "莫拉莱斯、玻利维亚、可可、原住民、总统、气候、海洋、权利"], "en": ["Coca Indigenous President Climate Ocean Rights", "Coca + indigenous + president + climate + ocean + rights", "Coca -> indigenous -> president -> climate -> ocean + rights", "Morales, Bolivia, coca, indigenous, president, climate, ocean, rights"]},
    "340": {"zh": ["独裁三国战争女性教育铁路悲剧", "独裁+三国战争+女性教育+铁路+悲剧", "独裁->三国战争->女性教育->铁路->悲剧", "洛佩斯、巴拉圭、独裁、三国战争、女性教育、铁路、悲剧"], "en": ["Dictatorship Triple Alliance War Women Education Railway Tragedy", "Dictatorship + triple alliance war + women education + railway + tragedy", "Dictatorship -> triple alliance war -> women education -> railway -> tragedy", "Lopez, Paraguay, dictatorship, triple alliance war, women education, railway, tragedy"]},
    "341": {"zh": ["肿瘤医生总统癌症烟草合法健康", "肿瘤医生+总统+癌症+烟草+合法+健康", "肿瘤医生->总统->癌症->烟草->合法->健康", "巴斯克斯、乌拉圭、肿瘤医生、总统、癌症、烟草、合法、健康"], "en": ["Oncologist President Cancer Tobacco Legal Health", "Oncologist + president + cancer + tobacco + legal + health", "Oncologist -> president -> cancer -> tobacco -> legal + health", "Vazquez, Uruguay, oncologist, president, cancer, tobacco, legal, health"]},
    "342": {"zh": ["庇隆主义工人埃维塔石油流亡回归", "庇隆主义+工人+埃维塔+石油+流亡+回归", "庇隆主义->工人->埃维塔->石油->流亡->回归", "庇隆、阿根廷、庇隆主义、工人、埃维塔、石油、流亡、回归"], "en": ["Peronism Workers Evita Oil Exile Return", "Peronism + workers + Evita + oil + exile + return", "Peronism -> workers -> Evita -> oil -> exile -> return", "Peron, Argentina, Peronism, workers, Evita, oil, exile, return"]},
    "343": {"zh": ["改革货币板私有化赦免里奥哈腐败", "改革+货币板+私有化+赦免+里奥哈+腐败", "改革->货币板->私有化->赦免->里奥哈->腐败", "梅内姆、阿根廷、改革、货币板、私有化、赦免、里奥哈、腐败"], "en": ["Reform Currency Board Privatization Amnesty Rioja Corruption", "Reform + currency board + privatization + amnesty + Rioja + corruption", "Reform -> currency board -> privatization -> amnesty -> Rioja + corruption", "Menem, Argentina, reform, currency board, privatization, amnesty, Rioja, corruption"]},
    "344": {"zh": ["社会主义选举政变自杀比诺切特新自由", "社会主义选举+政变+自杀+比诺切特+新自由", "社会主义选举->政变->自杀->比诺切特->新自由", "阿连德、智利、社会主义选举、政变、自杀、比诺切特、新自由"], "en": ["Socialist Election Coup Suicide Pinochet Neoliberal", "Socialist election + coup + suicide + Pinochet + neoliberal", "Socialist election -> coup -> suicide -> Pinochet -> neoliberal", "Allende, Chile, socialist election, coup, suicide, Pinochet, neoliberal"]},
    "345": {"zh": ["石油国有化土地改革卡德纳斯拉萨罗", "石油国有化+土地改革+卡德纳斯+拉萨罗", "石油国有化->土地改革->卡德纳斯->拉萨罗", "卡德纳斯、墨西哥、石油国有化、土地改革、卡德纳斯、拉萨罗"], "en": ["Oil Nationalization Land Reform Cardenas Lazaro", "Oil nationalization + land reform + Cardenas + Lazaro", "Oil nationalization -> land reform -> Cardenas -> Lazaro", "Cardenas, Mexico, oil nationalization, land reform, Cardenas, Lazaro"]},
    "346": {"zh": ["土地改革联合果品CIA政变切格瓦拉", "土地改革+联合果品+CIA政变+切+格瓦拉", "土地改革->联合果品->CIA政变->切->格瓦拉", "阿本斯、危地马拉、土地改革、联合果品、CIA政变、切、格瓦拉"], "en": ["Land Reform United Fruit CIA Coup Che Guevara", "Land reform + United Fruit + CIA coup + Che + Guevara", "Land reform -> United Fruit -> CIA coup -> Che -> Guevara", "Arbenz, Guatemala, land reform, United Fruit, CIA coup, Che, Guevara"]},
    "347": {"zh": ["大主教解放神学殉道内战真相圣人", "大主教+解放神学+殉道+内战+真相+圣人", "大主教->解放神学->殉道->内战->真相->圣人", "罗梅罗、萨尔瓦多、大主教、解放神学、殉道、内战、真相、圣人"], "en": ["Archbishop Liberation Theology Martyrdom Civil War Truth Saint", "Archbishop + liberation theology + martyrdom + civil war + truth + saint", "Archbishop -> liberation theology -> martyrdom -> civil war -> truth + saint", "Romero, El Salvador, archbishop, liberation theology, martyrdom, civil war, truth, saint"]},
    "348": {"zh": ["游击反美海军奥古斯托桑地诺英雄", "游击+反美+海军+奥古斯托+桑地诺+英雄", "游击->反美->海军->奥古斯托->桑地诺->英雄", "桑地诺、尼加拉瓜、游击、反美、海军、奥古斯托、桑地诺、英雄"], "en": ["Guerrilla Anti-US Navy Augusto Sandino Hero", "Guerrilla + anti-US + navy + Augusto + Sandino + hero", "Guerrilla -> anti-US -> navy -> Augusto -> Sandino -> hero", "Sandino, Nicaragua, guerrilla, anti-US, navy, Augusto, Sandino, hero"]},
    "349": {"zh": ["革命导弹危机医疗教育古巴弹道生存", "革命+导弹危机+医疗+教育+古巴+弹道+生存", "革命->导弹危机->医疗->教育->古巴->弹道->生存", "卡斯特罗、古巴、革命、导弹危机、医疗、教育、古巴、弹道、生存"], "en": ["Revolution Missile Crisis Healthcare Education Cuba Ballistic Survival", "Revolution + missile crisis + healthcare + education + Cuba + ballistic + survival", "Revolution -> missile crisis -> healthcare -> education -> Cuba -> ballistic + survival", "Castro, Cuba, revolution, missile crisis, healthcare, education, Cuba, ballistic, survival"]},
    "350": {"zh": ["医生独裁通顿马库特伏都恐怖贫困灾难", "医生独裁+通顿+马库特+伏都+恐怖+贫困+灾难", "医生独裁->通顿->马库特->伏都->恐怖->贫困->灾难", "杜瓦利埃、海地、医生独裁、通顿、马库特、伏都、恐怖、贫困、灾难"], "en": ["Doctor Dictatorship Tonton Macoute Voodoo Terror Poverty Disaster", "Doctor dictatorship + Tonton Macoute + Voodoo + terror + poverty + disaster", "Doctor dictatorship -> Tonton Macoute -> Voodoo -> terror -> poverty + disaster", "Duvalier, Haiti, doctor dictatorship, Tonton Macoute, Voodoo, terror, poverty, disaster"]},
    "351": {"zh": ["独裁欧根parsley大屠杀边境美国支持", "独裁+欧根+parsley大屠杀+边境+美国+支持", "独裁->欧根->parsley大屠杀->边境->美国->支持", "特鲁希略、多米尼加、独裁、欧根、parsley大屠杀、边境、美国支持"], "en": ["Dictatorship Trujillo Parsley Massacre Border US Support", "Dictatorship + Trujillo + parsley massacre + border + US support", "Dictatorship -> Trujillo -> parsley massacre -> border -> US support", "Trujillo, Dominican Republic, dictatorship, Trujillo, parsley massacre, border, US support"]},
    "352": {"zh": ["雷鬼拉斯塔非洲团结政治癌症传奇救赎", "雷鬼+拉斯塔+非洲团结+政治+癌症+传奇+救赎", "雷鬼->拉斯塔->非洲团结->政治->癌症->传奇->救赎", "马利、牙买加、雷鬼、拉斯塔、非洲团结、政治、癌症、传奇、救赎"], "en": ["Reggae Rastafari African Unity Politics Cancer Legend Redemption", "Reggae + Rastafari + African unity + politics + cancer + legend + redemption", "Reggae -> Rastafari -> African unity -> politics -> cancer -> legend + redemption", "Marley, Jamaica, reggae, Rastafari, African unity, politics, cancer, legend, redemption"]},
    "353": {"zh": ["梅蒂斯叛乱路易里尔曼尼托巴少数权利", "梅蒂斯+叛乱+路易里尔+曼尼托巴+少数权利", "梅蒂斯->叛乱->路易里尔->曼尼托巴->少数权利", "里尔、加拿大、梅蒂斯、叛乱、路易里尔、曼尼托巴、少数权利"], "en": ["Metis Rebellion Louis Riel Manitoba Minority Rights", "Metis + rebellion + Louis Riel + Manitoba + minority rights", "Metis -> rebellion -> Louis Riel -> Manitoba + minority rights", "Riel, Canada, Metis, rebellion, Louis Riel, Manitoba, minority rights"]},
    "354": {"zh": ["民权梦想非暴力蒙哥马利诺贝尔牧师", "民权+梦想+非暴力+蒙哥马利+诺贝尔+牧师", "民权->梦想->非暴力->蒙哥马利->诺贝尔->牧师", "金、美国、民权、梦想、非暴力、蒙哥马利、诺贝尔、牧师"], "en": ["Civil Rights Dream Non-Violence Montgomery Nobel Pastor", "Civil rights + dream + non-violence + Montgomery + Nobel + pastor", "Civil rights -> dream -> non-violence -> Montgomery -> Nobel + pastor", "King, USA, civil rights, dream, non-violence, Montgomery, Nobel, pastor"]},
    "355": {"zh": ["新政二战四大自由联合国轮椅最长", "新政+二战+四大自由+联合国+轮椅+最长", "新政->二战->四大自由->联合国->轮椅->最长", "罗斯福、美国、新政、二战、四大自由、联合国、轮椅、最长"], "en": ["New Deal WWII Four Freedoms UN Wheelchair Longest", "New Deal + WWII + four freedoms + UN + wheelchair + longest", "New Deal -> WWII -> four freedoms -> UN -> wheelchair + longest", "Roosevelt, USA, New Deal, WWII, four freedoms, UN, wheelchair, longest"]},
    "356": {"zh": ["自治渔业稀土气候冰盖独立丹麦博弈", "自治+渔业+稀土+气候+冰盖+独立+丹麦+博弈", "自治->渔业->稀土->气候->冰盖->独立->丹麦->博弈", "克努森、格陵兰、自治、渔业、稀土、气候、冰盖、独立、丹麦、博弈"], "en": ["Autonomy Fisheries Rare Earth Climate Ice Independence Denmark Game", "Autonomy + fisheries + rare earth + climate + ice + independence + Denmark + game", "Autonomy -> fisheries -> rare earth -> climate -> ice -> independence + Denmark + game", "Knudsen, Greenland, autonomy, fisheries, rare earth, climate, ice, independence, Denmark, game"]},
}

# ============================================================
# 2. 定义 95 位人物完整 v6 Schema 数据
# ============================================================

PHASE_13_16_FIGURES = [
    # Phase 13.1: 高加索三国 (6)
    {
        "code": "GE-PHI-001",
        "prefix": "GE",
        "topic": "PHI",
        "name_zh": "格鲁吉亚·伊利亚恰瓦泽：民族精神重生",
        "name_en": "Ilia Chavchavadze: National Spirit Rebirth",
        "description_zh": "伊利亚·恰瓦泽是格鲁吉亚民族觉醒运动的领袖、诗人、作家、政治家。他领导了19世纪格鲁吉亚的文化复兴运动，通过文学、教育和政治活动唤醒民族意识，反抗俄国殖民统治，为格鲁吉亚的独立奠定基础。",
        "description_en": "Ilia Chavchavadze was a leader of the Georgian national awakening movement, poet, writer, and politician. He led the 19th-century Georgian cultural renaissance, awakening national consciousness through literature, education, and political activities, resisting Russian colonial rule and laying the foundation for Georgia's independence.",
        "reason_zh": "代表高加索地区的民族觉醒，展示了正教文明圈在殖民压迫下的文化复兴路径，对格鲁吉亚和整个高加索地区的民族认同构建有深远影响。",
        "reason_en": "Represents the national awakening in the Caucasus, demonstrating the path of cultural revival under colonial oppression in the Orthodox civilization sphere, with profound impact on national identity construction in Georgia and the entire Caucasus region.",
        "steps_zh": ["研究伊利亚·恰瓦泽的诗歌《英雄》《幽谷》和小说《强盗卡科》", "分析其民族觉醒思想与东正教传统的对话", "探讨19世纪高加索地区的民族复兴运动", "评估其创办《伊韦利亚》杂志的文化影响", "总结恰瓦泽思想在当代格鲁吉亚独立运动中的延续"],
        "steps_en": ["Study Ilia Chavchavadze's poetry 'The Hero' and 'The Valley' and his novel 'Robber Kako'", "Analyze the dialogue between his national awakening thought and Orthodox tradition", "Explore the national revival movement in the Caucasus in the 19th century", "Evaluate the cultural impact of his founding of 'Iberia' magazine", "Summarize the continuity of Chavchavadze's thought in the contemporary Georgian independence movement"],
        "expected_zh": "掌握恰瓦泽的核心民族复兴思想，理解高加索地区民族觉醒的发展路径，评估其对格鲁吉亚民族认同构建和独立运动的历史影响。",
        "expected_en": "Master Chavchavadze's core national revival thought, understand the development path of national awakening in the Caucasus, and evaluate his historical impact on Georgian national identity construction and the independence movement.",
        "case_zh": "伊利亚·恰瓦泽在 1869 年创办《伊韦利亚》杂志，成为格鲁吉亚民族复兴运动的核心舆论阵地，通过文学、历史和文化研究唤醒民族意识，直接推动了格鲁吉亚的语言恢复和民族认同重构。",
        "case_en": "In 1869, Ilia Chavchavadze founded 'Iberia' magazine, becoming the core public opinion platform of the Georgian national revival movement. Through literature, history, and cultural studies, he awakened national consciousness, directly promoting the restoration of Georgian language and the reconstruction of national identity.",
        "modes": [276, 262, 237, 1, 153],
        "nationality": "Georgia",
        "civilization_sphere": "Caucasus/Orthodox",
        "time_period_standardized": "1837-1907",
        "wiki_id": "Ilia_Chavchavadze",
        "primary_language": "Georgian",
        "intellectual_tradition": "National Awakening",
        "cross_cultural_impact": "Georgia's national awakening leader, influenced Caucasus nationalism",
        "legacy_type": "cultural",
        "legal_system": "大陆法",
        "education_tradition": "西方",
        "scientific_contribution": "否",
        "artistic_legacy": "是: 浪漫主义/民族文学",
        "environmental_stewardship": "否",
        "gender_role_innovation": "否",
        "diaspora_network_type": "文化",
        "digital_adaptation": "滞后",
        "regional_integration": "CIS",
        "conflict_resolution_mechanism": "抵抗革命"
    },
    {
        "code": "GE-STA-001",
        "prefix": "GE",
        "topic": "STA",
        "name_zh": "格鲁吉亚·斯大林：苏联化与格鲁吉亚本土化",
        "name_en": "Georgia Stalin: Sovietization & Georgian Indigenization",
        "description_zh": "约瑟夫·斯大林 (1878-1953) 生于格鲁吉亚哥里，作为苏联最高领导人推行全面苏联化政策，同时在格鲁吉亚实施\"本土化\"策略，培养格鲁吉亚籍干部，推广格鲁吉亚语言文化，形成独特的\"格鲁吉亚式斯大林主义\"。",
        "description_en": "Joseph Stalin (1878-1953) born in Gori, Georgia, as Soviet supreme leader implemented comprehensive Sovietization policies while pursuing \"indigenization\" in Georgia, cultivating Georgian cadres, promoting Georgian language and culture, creating a unique \"Georgian-style Stalinism.\"",
        "reason_zh": "斯大林是格鲁吉亚裔苏联领袖，其统治展示了帝国中心与边缘民族地区的复杂互动，既是苏联化的推行者又是格鲁吉亚本土化的受益者，体现高加索地区在苏联体制中的特殊地位。",
        "reason_en": "Stalin as Georgian-origin Soviet leader demonstrates complex interaction between imperial center and peripheral ethnic regions - both driver of Sovietization and beneficiary of Georgian indigenization, embodying Caucasus's special status in Soviet system.",
        "steps_zh": ["分析斯大林早年格鲁吉亚革命经历与马克思主义接受", "研究1920s格鲁吉亚本土化政策与语言文化推广", "探讨斯大林清洗中格鲁吉亚精英的命运", "评估二战时期格鲁吉亚作为后方基地的贡献", "总结斯大林死后格鲁吉亚去斯大林化与民族记忆"],
        "steps_en": ["Analyze Stalin's early Georgian revolutionary experience and Marxist adoption", "Study 1920s Georgian indigenization policies and language-culture promotion", "Explore fate of Georgian elites during Stalin's purges", "Evaluate Georgia's contribution as rear base during WWII", "Summarize post-Stalin de-Stalinization in Georgia and ethnic memory"],
        "expected_zh": "理解斯大林作为格鲁吉亚裔苏联领袖的双重身份张力，掌握苏联化与本土化在高加索地区的辩证关系，评估其对后苏联时代格鲁吉亚民族认同的深远影响。",
        "expected_en": "Understand the dual identity tension of Stalin as Georgian-origin Soviet leader, grasp the dialectic of Sovietization and indigenization in the Caucasus, evaluate its profound impact on post-Soviet Georgian national identity.",
        "case_zh": "1921 斯大林任格鲁吉亚事务人民委员，推行本土化；1930s 大清洗中格鲁吉亚精英大量遇害；1941-1945 格鲁吉亚作为苏联后方提供 70 万士兵；1953 斯大林死后格鲁吉亚爆发反苏示威。苏联化与本土化辩证张力永存。",
        "case_en": "1921 Stalin as People's Commissar for Georgian Affairs promoted indigenization; 1930s Great Purge decimated Georgian elites; 1941-1945 Georgia as Soviet rear provided 700K soldiers; 1953 post-Stalin Georgia erupted in anti-Soviet protests. Sovietization-indigenization dialectical tension endures.",
        "modes": [263, 262, 237, 1, 153],
        "nationality": "Georgia",
        "civilization_sphere": "Caucasus/Orthodox",
        "time_period_standardized": "1921-1953",
        "wiki_id": "Joseph_Stalin;Georgian_Sovietization;Indigenization_policy",
        "primary_language": "Georgian/Russian",
        "intellectual_tradition": "Marxism-Leninism / Georgian National Communism",
        "cross_cultural_impact": "Sovietization driver; Georgian indigenization beneficiary; Caucasus